package lifecycle

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/OWNER/sbctl/internal/config"
	"github.com/OWNER/sbctl/internal/projectconfig"
	"github.com/OWNER/sbctl/internal/registry"
	"github.com/OWNER/sbctl/internal/secrets"
	"github.com/OWNER/sbctl/internal/units"
)

func TestStripManagedSettings(t *testing.T) {
	body := "# Do not edit this file manually!\n" +
		"max_locks_per_transaction = '2147483640'\n" +
		"  Statement_Timeout = '5s'\n" +
		"cron.log_statement = 'off'\n" +
		"unmanaged_extension.setting = 'x'\n" +
		"work_mem = '8MB'\n"
	got, changed := stripManagedSettings(body)
	if !changed || got != "# Do not edit this file manually!\nunmanaged_extension.setting = 'x'\n" {
		t.Fatalf("changed=%v body=%q", changed, got)
	}
	if again, changed := stripManagedSettings(got); changed || again != got {
		t.Fatalf("a clean file must stay as it is: %q", again)
	}
}

// fakeSup records what the plane does to the units; a postgres unit that was told to start
// reports failed, like one that cannot start on its settings.
type fakeSup struct {
	mu     sync.Mutex
	log    []string
	failed bool
}

func (f *fakeSup) rec(s string) { f.mu.Lock(); f.log = append(f.log, s); f.mu.Unlock() }
func (f *fakeSup) Render(_ context.Context, s units.Spec) error {
	f.rec("render " + s.Unit())
	return nil
}
func (f *fakeSup) Start(_ context.Context, u string) error { f.rec("start " + u); return nil }
func (f *fakeSup) Stop(_ context.Context, u string) error  { f.rec("stop " + u); return nil }
func (f *fakeSup) Status(context.Context, string) (units.Status, error) {
	return units.Status{State: units.StateFailed}, nil
}
func (f *fakeSup) Remove(context.Context, string) error { return nil }

func (f *fakeSup) index(s string) int {
	f.mu.Lock()
	defer f.mu.Unlock()
	for i, l := range f.log {
		if l == s {
			return i
		}
	}
	return -1
}

// A cluster that cannot start on a setting Postgres accepted in ALTER SYSTEM must be started
// again on the saved settings: the project stops, the managed lines leave postgresql.auto.conf
// offline, and the cluster unit starts (its wait then fails here only because there is no
// real Postgres behind the fake).
func TestRecoverPostgresClearsAutoConfAndStartsTheCluster(t *testing.T) {
	cfg := config.Default()
	cfg.StateDir = shortTempDir(t)
	cfg.Domain = "example.test"
	cfg.BinPath = "/usr/local/bin/sbctl"
	sup := &fakeSup{}
	pl := NewPostgresPlane(cfg, sup, fakeArts{}, registry.NewMemory(), PlaneOptions{})
	p := testProject(cfg, "abcdefghijklmnopqrst", 2)
	keys := testKeys(t, p.Ref)
	pp := pl.paths(p)
	if err := os.MkdirAll(pp.Data, 0o700); err != nil {
		t.Fatal(err)
	}
	auto := filepath.Join(pp.Data, "postgresql.auto.conf")
	if err := os.WriteFile(auto, []byte("# managed by ALTER SYSTEM\nmax_locks_per_transaction = '2147483640'\nlog_connections = 'on'\nextension.keep = 'yes'\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	err := pl.RecoverPostgres(context.Background(), p, keys)
	if err == nil {
		t.Fatal("the fake cluster never answers; the start must report it")
	}
	b, _ := os.ReadFile(auto)
	if strings.Contains(string(b), "max_locks_per_transaction") || strings.Contains(string(b), "log_connections") || !strings.Contains(string(b), "extension.keep") {
		t.Fatalf("auto.conf after recovery:\n%s", b)
	}
	pg := config.UnitName(config.SvcPostgres, p.Ref)
	stop, start := sup.index("stop "+pg), sup.index("start "+pg)
	if stop < 0 || start < 0 || start < stop {
		t.Fatalf("the cluster must stop, then start again: %v", sup.log)
	}
	// The cluster starts from rendered files, so the saved settings are in its unit.
	if sup.index("render "+pg) < 0 {
		t.Fatalf("the unit was not rendered: %v", sup.log)
	}
}

func TestCheckRenderRefusesWhatTheUnitCannotCarry(t *testing.T) {
	pl, cfg := testPlane(t)
	p := testProject(cfg, "abcdefghijklmnopqrst", 2)
	keys := testKeys(t, p.Ref)
	pl.opts.Settings = &fakeSettings{auth: map[string]string{"GOTRUE_SMS_TEMPLATE": "Your code\nis {{ .Code }}"}}
	if err := pl.CheckRender(context.Background(), p, keys, projectconfig.Auth); err == nil || !strings.Contains(err.Error(), "newline") {
		t.Fatalf("auth with a line break in an env value: %v", err)
	}
	if err := pl.CheckRender(context.Background(), p, keys, projectconfig.Realtime); err != nil {
		t.Fatalf("Realtime renders no unit: %v", err)
	}
	pl.opts.Settings = &fakeSettings{auth: map[string]string{"GOTRUE_SITE_URL": "https://app.example.com"}}
	if err := pl.CheckRender(context.Background(), p, keys, projectconfig.Auth); err != nil {
		t.Fatal(err)
	}
}

type recPlane struct {
	*cfgPlane
	order      []string
	recoverErr error
}

func (r *recPlane) RecoverPostgres(context.Context, *registry.Project, *secrets.ProjectKeys) error {
	r.order = append(r.order, "recover")
	return r.recoverErr
}

func (r *recPlane) ApplyPostgresSettings(ctx context.Context, p *registry.Project, k *secrets.ProjectKeys, restart bool, before func(context.Context)) (bool, error) {
	r.order = append(r.order, "apply")
	return r.cfgPlane.ApplyPostgresSettings(ctx, p, k, restart, before)
}

func TestApplyConfigRecoverStartsTheClusterBeforeApplying(t *testing.T) {
	h, cp, _, _ := configHarness(t)
	rp := &recPlane{cfgPlane: cp}
	h.e.plane = rp
	ctx := context.Background()
	p := h.create(t)

	if _, err := h.e.ApplyConfig(ctx, p.Ref, projectconfig.Postgres, ApplyOptions{RestartDatabase: true}); err != nil {
		t.Fatal(err)
	}
	if strings.Join(rp.order, ",") != "apply" {
		t.Fatalf("a plain apply must not recover: %v", rp.order)
	}
	rp.order = nil
	if _, err := h.e.ApplyConfig(ctx, p.Ref, projectconfig.Postgres, ApplyOptions{RestartDatabase: true, Recover: true}); err != nil {
		t.Fatal(err)
	}
	if strings.Join(rp.order, ",") != "recover,apply" || !cp.pgCalls[len(cp.pgCalls)-1] {
		t.Fatalf("order %v, restart flags %v", rp.order, cp.pgCalls)
	}
	// A cluster that cannot be brought back is an error, and the settings are not applied.
	rp.order = nil
	rp.recoverErr = errors.New("still down")
	if _, err := h.e.ApplyConfig(ctx, p.Ref, projectconfig.Postgres, ApplyOptions{Recover: true}); err == nil || !strings.Contains(err.Error(), "still down") {
		t.Fatalf("err = %v", err)
	}
	if strings.Join(rp.order, ",") != "recover" {
		t.Fatalf("order %v", rp.order)
	}
	// Recover is ignored by other services.
	rp.order = nil
	if _, err := h.e.ApplyConfig(ctx, p.Ref, projectconfig.Auth, ApplyOptions{Recover: true}); err != nil || len(rp.order) != 0 {
		t.Fatalf("auth with Recover: %v %v", err, rp.order)
	}
}

type checkPlane struct {
	*cfgPlane
	checked []projectconfig.Service
	err     error
}

func (c *checkPlane) CheckRender(_ context.Context, _ *registry.Project, _ *secrets.ProjectKeys, svc projectconfig.Service) error {
	c.checked = append(c.checked, svc)
	return c.err
}

// A paused project accepts settings that render; one that cannot be rendered fails the save,
// not the resume.
func TestApplyConfigOfAPausedProjectRendersWithoutStarting(t *testing.T) {
	h, cp, _, _ := configHarness(t)
	chk := &checkPlane{cfgPlane: cp}
	h.e.plane = chk
	ctx := context.Background()
	p := h.create(t)
	h.reg.SetProjectStatus(ctx, p.Ref, registry.StatusInactive)
	cp.services = nil

	res, err := h.e.ApplyConfig(ctx, p.Ref, projectconfig.Auth, ApplyOptions{})
	if err != nil || res.Applied || len(chk.checked) != 1 || chk.checked[0] != projectconfig.Auth || len(cp.services) != 0 {
		t.Fatalf("%+v %v checked=%v services=%v", res, err, chk.checked, cp.services)
	}
	chk.err = errors.New("GOTRUE_SMS_TEMPLATE contains a newline")
	if _, err := h.e.ApplyConfig(ctx, p.Ref, projectconfig.Auth, ApplyOptions{}); err == nil || !strings.Contains(err.Error(), "newline") {
		t.Fatalf("an unrenderable setting of a paused project must fail the save: %v", err)
	}
}

// Revoking a default key must not survive a key rotation: the rotated defaults are new keys.
func TestRotateKeysRevivesRevokedDefaultKeys(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	p := h.create(t)
	old, _ := h.e.Keys(ctx, p.Ref)
	for _, typ := range []string{secrets.KeyTypePublishable, secrets.KeyTypeSecret} {
		rec := secrets.APIKeyRecord{ID: secrets.KeyID(p.Ref, secrets.DefaultKeyName, typ), Name: secrets.DefaultKeyName, Type: typ, Default: true, Revoked: true}
		b, _ := secrets.MarshalRecord(rec)
		sealed, _ := h.sec.Seal(b)
		if err := h.reg.PutSecret(ctx, p.Ref, secrets.RecordSecretName(rec.ID), sealed); err != nil {
			t.Fatal(err)
		}
	}
	if k, _ := h.e.Keys(ctx, p.Ref); len(k.OpaqueKeys(p.Ref)) != 0 {
		t.Fatalf("both default keys should be revoked: %v", k.OpaqueKeys(p.Ref))
	}
	nk, err := h.e.RotateKeys(ctx, p.Ref)
	if err != nil {
		t.Fatal(err)
	}
	stored, _ := h.e.Keys(ctx, p.Ref)
	got := stored.OpaqueKeys(p.Ref)
	if len(got) != 2 || nk.SecretKey == old.SecretKey {
		t.Fatalf("the rotated default keys must be active: %v", got)
	}
	found := map[string]bool{}
	for _, k := range got {
		found[k.Key] = true
	}
	if !found[nk.SecretKey] || !found[nk.PublishableKey] {
		t.Fatalf("active keys are not the rotated ones: %v", got)
	}
}
