"""Generate every Supavise brand asset from one geometry.

    python3 brand/build.py

Writes brand/mark/*.svg, brand/lockups/*.svg, brand/favicon.svg, brand/social/*.svg, brand/readme/*.svg
(the README banner, architecture diagram, feature grid, path cards, heading glyph and footer, each in a dark
and a light variant, narrow single-column variants of the feature grid and the path cards for phones, plus four
badges) and brand/variants.html.
Needs fontTools (pip install fonttools) and network access the first time,
to fetch Manrope (OFL) from the google/fonts repo into a temp dir.

Mark geometry, in a 1000-unit box. Two hooks, each the 180-degree rotation of the other:
  a top bar with a stub down its left side, a bottom bar with a stub up its right side. They are drawn
  upright, then leaned by a shear of tan(LEAN) about the middle, with the stubs widened by sqrt(1+k^2) so every
  stroke measures BAR across. The stubs reach past the middle by OV; each stub's far end is cut on a slant so
  the pockets between the hooks narrow to points a hairline GAP from the opposite bar. Those pockets and the
  channel between them are the mark's negative space: a zigzag, the same structure as a bolt.
"""
import math, os, tempfile, urllib.request
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRAND = "#00e0c4"   # signal teal: the mark on black and dark grounds, and the ground that carries an ink mark
INK = "#0b0b0b"     # the mark on light surfaces, and the black of every brand ground
WHITE = "#ffffff"

# ---- mark ----------------------------------------------------------------
H, BAR, LEAN, W = 680, 160, 20, 800     # height, stroke, lean (degrees), width including the lean
OV, GAP = 40, 80                        # stub overlap past the middle, hairline gap at the pocket tips
MARK_PAD = 10                           # viewBox bleed so the edges are not clipped by anti-aliasing

def hooks(h=H, bar=BAR, deg=LEAN, w=W, ov=OV, g=GAP, top=None, bottom=None):
    k = math.tan(math.radians(deg))
    yc = 500
    yt, yb = yc - h / 2, yc + h / 2
    w0 = w - k * h
    x0, x1 = 500 - w0 / 2, 500 + w0 / 2
    sw = bar * math.sqrt(1 + k * k)
    reach = yb - bar - g
    a = [(x0, yt), (x1, yt), (x1, yt + bar), (x0 + sw, yt + bar), (x0 + sw, yc + ov), (x0, reach)]
    b = [(x1, yb), (x0, yb), (x0, yb - bar), (x1 - sw, yb - bar), (x1 - sw, yc - ov), (x1, 2 * yc - reach)]
    sets = [[(x + (yc - y) * k, y) for x, y in p] for p in (a, b)]
    xs = [x for s in sets for x, _ in s]
    path = " ".join("M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in s) + " Z" for s in sets)
    return path, (min(xs), yt, max(xs), yb)

MARK, BBOX = hooks()
MW, MH = BBOX[2] - BBOX[0], BBOX[3] - BBOX[1]     # ink width and height
VB = f"{BBOX[0]-MARK_PAD:.1f} {BBOX[1]-MARK_PAD:.1f} {MW+2*MARK_PAD:.1f} {MH+2*MARK_PAD:.1f}"

def mark_svg(color, title):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VB}" role="img" aria-label="Supavise mark">
  <title>Supavise mark ({title})</title>
  <desc>Two interlocking hooks leaning 20 degrees. One flat color, no strokes, no gradients. The space between the hooks is a zigzag, like a bolt. Generated by brand/build.py.</desc>
  <path fill="{color}" d="{MARK}"/>
</svg>
'''

# The favicon is the mark at tab size on a rounded teal tile. Width 46 of 64, centered. At 16px the hairline
# gap is about 1px, which is the smallest it holds; below that use the tile alone.
def favicon_svg():
    fw = 46; s = fw / MW
    tx, ty = 32 - (BBOX[0] + MW / 2) * s, 32 - (BBOX[1] + MH / 2) * s
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <title>Supavise</title>
  <!-- Signal teal and ink as literals because an SVG file cannot reach any CSS tokens. A solid tile, not the
       bare mark, so it holds on light and dark tab strips alike. Generated by brand/build.py. -->
  <rect width="64" height="64" rx="14" fill="{BRAND}"/>
  <path fill="{INK}" transform="translate({tx:.3f} {ty:.3f}) scale({s:.5f})" d="{MARK}"/>
</svg>
'''

# ---- wordmark ------------------------------------------------------------
# Manrope ExtraBold, the face the Allocait lockup uses, so the family shares one voice. The mark is the S.
FONT_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/manrope/Manrope%5Bwght%5D.ttf"
TRACK = -70       # -0.035em at 2000 upem, as Allocait
LGAP = 215        # mark's right ink edge to the "u" stem
PAD = 20          # lockup viewBox bleed

def load_font():
    cache = os.path.join(tempfile.gettempdir(), "Manrope-800.ttf")
    if not os.path.exists(cache):
        src = os.path.join(tempfile.gettempdir(), "Manrope[wght].ttf")
        urllib.request.urlretrieve(FONT_URL, src)
        instancer.instantiateVariableFont(TTFont(src), {"wght": 800}).save(cache)
    return TTFont(cache)

def build_lockup():
    f = load_font(); gs = f.getGlyphSet(); cmap = f.getBestCmap()
    cap = f["OS/2"].sCapHeight
    glyphs = [gs[cmap[ord(c)]] for c in "upavise"]
    bs = []
    for g in glyphs:
        bp = BoundsPen(gs); g.draw(bp); bs.append(bp.bounds)
    top = max(cap, max(b[3] for b in bs))              # the i dot clears the cap line
    depth = -min(b[1] for b in bs)                     # the p descender
    base = PAD + top
    s = cap / MH                                       # mark height equals cap height; its edges are flat
    mark_w = MW * s
    x = PAD + mark_w + LGAP - bs[0][0]
    parts = []
    for g, b in zip(glyphs, bs):
        pen = SVGPathPen(gs); g.draw(TransformPen(pen, (1, 0, 0, -1, x, base)))
        parts.append(pen.getCommands()); last = x + b[2]; x += g.width + TRACK
    return dict(s=s, w=round(last + PAD), h=round(base + depth + PAD), word=" ".join(parts), base=base, cap=cap)

def lockup_body(mark_c, word_c, k):
    s = k["s"]
    tx, ty = PAD - BBOX[0] * s, k["base"] - k["cap"] - BBOX[1] * s
    return (f'<path fill="{mark_c}" transform="translate({tx:.3f} {ty:.3f}) scale({s:.5f})" d="{MARK}"/>'
            f'<path fill="{word_c}" d="{k["word"]}"/>')

def lockup_svg(mark_c, word_c, title, k):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {k["w"]} {k["h"]}" role="img" aria-label="Supavise">
  <title>Supavise ({title})</title>
  <desc>Horizontal lockup. The mark is the initial S; "upavise" is Manrope ExtraBold outlined to paths, tracked -3.5%. Mark height is the cap height. Do not re-space. Generated by brand/build.py.</desc>
  {lockup_body(mark_c, word_c, k)}
</svg>
'''

# ---- social --------------------------------------------------------------
SOCIAL, BLACK = BRAND, INK
AVATAR, HEADER, OG, GH = 800, (1500, 500), (1200, 630), (1280, 640)

def nested(x, y, w, h, viewbox, body):
    return f'<svg x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" viewBox="{viewbox}">{body}</svg>'

def mark_at(cx, cy, glyph_h, color):
    # glyph_h is the ink height; the viewBox adds MARK_PAD on each side.
    sc = glyph_h / MH
    w, h = (MW + 2 * MARK_PAD) * sc, (MH + 2 * MARK_PAD) * sc
    return nested(cx - w / 2, cy - h / 2, w, h, VB, f'<path fill="{color}" d="{MARK}"/>')

def lockup_at(cx, cy, lock_h, mark_c, word_c, k):
    lw = lock_h * k["w"] / k["h"]
    return nested(cx - lw / 2, cy - lock_h / 2, lw, lock_h, f'0 0 {k["w"]} {k["h"]}', lockup_body(mark_c, word_c, k))

def canvas(w, h, bg, title, body):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">
  <title>Supavise {title}</title>
  <rect width="{w}" height="{h}" fill="{bg}"/>
  {body}
</svg>
'''

def avatar_svg(bg, fg, title):
    # Mark 56% of the side wide: the avatar crops to a circle on X, LinkedIn, GitHub and Bluesky.
    gh = AVATAR * 0.56 / (MW / MH)
    return canvas(AVATAR, AVATAR, bg, f"avatar ({title})", mark_at(AVATAR / 2, AVATAR / 2, gh, fg))

def apple_touch_svg():
    return canvas(180, 180, BRAND, "apple touch icon", mark_at(90, 90, 124 / (MW / MH), INK))

def header_svgs(k):
    W_, H_ = HEADER
    lock = lambda mc, wc: lockup_at(W_ / 2, H_ / 2, 100, mc, wc, k)
    return {
        # The mark oversized off the right edge, the zigzag in frame.
        "slice": canvas(W_, H_, BLACK, "X header (slice)", mark_at(1330, 210, 700, SOCIAL) + lock(SOCIAL, WHITE)),
        "black": canvas(W_, H_, BLACK, "X header (black)", lock(SOCIAL, WHITE)),
        "teal": canvas(W_, H_, SOCIAL, "X header (teal)", lock(INK, INK)),
    }

def og_svg(k, size=OG, name="link preview"):
    W_, H_ = size
    return canvas(W_, H_, BLACK, name,
                  mark_at(W_ - 190, H_ / 2 - 10, H_ * 0.86, SOCIAL) + lockup_at(W_ * 0.33, H_ / 2, 120, SOCIAL, WHITE, k))

# ---- README graphics -----------------------------------------------------
# Banner and architecture diagram, each in a dark and a light variant for <picture>. GitHub shows SVG through
# <img>, so there are no webfonts, external references or foreignObject: the lockup is outlined paths and every
# other word is live text in a system font stack. Brand color is teal on black and ink on light; boxes and
# secondary text are neutral grays, picked to keep at least 4.5:1 against their ground.
SANS = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, Helvetica, Arial, sans-serif"
MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
TAGLINE = "Supabase orgs and projects, self-hosted."
SUBLINE = "One server. Open source. Not affiliated with Supabase Inc."

THEMES = {
    "dark":  dict(bg=BLACK, accent=BRAND, word=WHITE, text=WHITE, sub="#a3a3a3", box="#151515", line="#3a3a3a",
                  mark_c=BRAND, word_c=WHITE, ghost="#141414", onaccent=INK),
    "light": dict(bg=WHITE, accent=INK, word=INK, text=INK, sub="#595959", box="#f4f4f4", line="#c9c9c9",
                  mark_c=INK, word_c=INK, ghost="#f3f3f3", onaccent=WHITE),
}

def esc(t):
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def text(x, y, t, size, fill, weight=400, anchor="start", family=SANS, spacing=None):
    ls = f' letter-spacing="{spacing}"' if spacing is not None else ""
    return (f'<text x="{x:g}" y="{y:g}" font-family="{family}" font-size="{size:g}" font-weight="{weight}" '
            f'fill="{fill}" text-anchor="{anchor}"{ls}>{esc(t)}</text>')

def banner_svg(theme, k):
    c = THEMES[theme]; W_, H_ = 1280, 320
    lock_h = 84; lw = lock_h * k["w"] / k["h"]
    x0 = 96; top = 70
    body = (mark_at(W_ - 70, H_ / 2, 400, c["ghost"])
            + lockup_at(x0 - 20 * lock_h / k["h"] + lw / 2, top + lock_h / 2, lock_h, c["mark_c"], c["word_c"], k)
            + text(x0, top + lock_h + 54, TAGLINE, 34, c["text"], 600, spacing=-0.3)
            + text(x0, top + lock_h + 90, SUBLINE, 18, c["sub"]))
    return canvas(W_, H_, c["bg"], f"README banner ({theme})", body)

def arch_svg(theme):
    c = THEMES[theme]; W_, H_ = 1200, 590
    out = []
    add = out.append
    SW = 1.5                                   # one stroke width for every box and line
    def box(x, y, w, h, fill=None, stroke=None, sw=SW, rx=10, dash=None):
        d = f' stroke-dasharray="{dash}"' if dash else ""
        return (f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="{rx}" fill="{fill or c["box"]}" '
                f'stroke="{stroke or c["line"]}" stroke-width="{sw}"{d}/>')
    def label(x, y, t, anchor="start"):
        return text(x, y, t, 13, c["sub"], 700, anchor, spacing=1.4)
    def arrow(x1, y1, x2, y2, color=None):
        col = color or c["accent"]
        dx = 1 if x2 > x1 else 0; dy = 1 if y2 > y1 else 0
        if dx:
            head = f'{x2:g},{y2:g} {x2-9:g},{y2-5:g} {x2-9:g},{y2+5:g}'; x2 -= 8
        else:
            head = f'{x2:g},{y2:g} {x2-5:g},{y2-9:g} {x2+5:g},{y2-9:g}'; y2 -= 8
        return (f'<line x1="{x1:g}" y1="{y1:g}" x2="{x2:g}" y2="{y2:g}" stroke="{col}" stroke-width="{SW}"/>'
                f'<polygon points="{head}" fill="{col}"/>')
    def darrow(x1, y1, x2, y2):                 # arrowheads at both ends, for request and response traffic
        return arrow(x1, y1, x2, y2) + arrow(x2, y2, x1, y1)

    CX, CW = 24, 192                    # clients column
    NX, NW = 296, 584                   # node container
    BX, BW = 976, 200                   # backups column
    TOP, BOT = 80, 550

    # column labels
    add(label(CX, 52, "CLIENTS")); add(label(NX, 52, "SUPAVISE NODE")); add(text(NX + NW, 52, "one Linux server", 13, c["sub"], 400, "end"))
    add(label(BX, 52, "BACKUPS"))

    # clients
    # The first client is the browser: Studio itself runs on the node (the shared row below).
    clients = [("Browser", "Supabase Studio"), ("Supabase CLI", "link, push, deploy"),
               ("MCP server", "AI assistants"), ("Your apps", "supabase-js")]
    ch, cg = 80, 24
    y0 = (TOP + BOT) / 2 - (4 * ch + 3 * cg) / 2
    for i, (t, sub) in enumerate(clients):
        y = y0 + i * (ch + cg)
        add(box(CX, y, CW, ch))
        add(text(CX + 20, y + 36, t, 17, c["text"], 600))
        add(text(CX + 20, y + 59, sub, 14, c["sub"]))
    # arrows from the clients into the node: one bus, so the lines do not fan out
    mid = (TOP + BOT) / 2
    bus = CX + CW + 18
    ys = [y0 + i * (ch + cg) + ch / 2 for i in range(4)]
    for y in ys:
        add(f'<line x1="{CX+CW:g}" y1="{y:g}" x2="{bus:g}" y2="{y:g}" stroke="{c["accent"]}" stroke-width="{SW}"/>')
    add(f'<line x1="{bus:g}" y1="{ys[0]:g}" x2="{bus:g}" y2="{ys[-1]:g}" stroke="{c["accent"]}" stroke-width="{SW}"/>')
    add(arrow(bus, mid, NX, mid))
    add(text((bus + NX) / 2, mid - 10, "HTTPS", 12, c["sub"], 500, "middle", spacing=0.4))

    # node container
    add(box(NX, TOP, NW, BOT - TOP, fill="none", stroke=c["accent"], sw=SW, rx=14))
    ix, iw = NX + 24, NW - 48

    # the supavise binary
    by, bh = TOP + 24, 148
    add(box(ix, by, iw, bh, sw=2, stroke=c["accent"]))
    # The binary's name in monospace, with no mark beside it: mark plus live type would read as a re-set lockup.
    add(text(ix + 20, by + 37, "supavise", 19, c["text"], 700, family=MONO))
    add(text(ix + iw - 20, by + 36, "one Go binary", 14, c["sub"], 400, "end"))
    chips = [("HTTPS", "proxy"), ("Management", "API"), ("Project", "lifecycle"), ("Backup", "service")]
    gap = 12; cw_ = (iw - 40 - 3 * gap) / 4
    for i, (a, b) in enumerate(chips):
        x = ix + 20 + i * (cw_ + gap); y = by + 64
        add(box(x, y, cw_, 64, fill=c["bg"], rx=8))
        add(text(x + cw_ / 2, y + 28, a, 15, c["text"], 600, "middle"))
        add(text(x + cw_ / 2, y + 48, b, 15, c["text"], 600, "middle"))

    # per-project services
    py = by + bh + 44
    add(arrow(NX + NW / 2, by + bh, NX + NW / 2, py - 10, c["accent"]))
    add(label(ix, py + 8, "PER PROJECT"))
    pw = (iw - 2 * 16) / 3; ph = 118
    for i, name in enumerate("ABC"):
        x = ix + i * (pw + 16); y = py + 22
        add(box(x, y, pw, ph))
        add(text(x + 18, y + 31, f"Project {name}", 16, c["text"], 600))
        for j, svc in enumerate(["Postgres", "Auth", "REST"]):
            yy = y + 56 + j * 24
            add(f'<rect x="{x+18:g}" y="{yy-8:g}" width="8" height="8" fill="{c["accent"]}"/>')
            add(text(x + 36, yy, svc, 14, c["sub"]))

    # shared services
    sy = py + 22 + ph + 28
    add(label(ix, sy + 6, "SHARED BY ALL PROJECTS"))
    shared = ["Supavisor", "Realtime", "Storage", "Edge Runtime", "Studio"]
    # Pill widths follow their labels: an estimated width (0.62 em per character, wider than any system face's
    # semibold average) plus an equal share of what is left, so "Edge Runtime" gets the padding the others get.
    sg = 8; est = [len(s_) * 14 * 0.62 for s_ in shared]
    extra = (iw - (len(shared) - 1) * sg - sum(est)) / len(shared)
    x = ix
    for s_, e in zip(shared, est):
        w_ = e + extra; y = sy + 18
        add(box(x, y, w_, 44, rx=8))
        add(text(x + w_ / 2, y + 27, s_, 14, c["text"], 600, "middle"))
        x += w_ + sg

    # backups
    gx0, gx1 = NX + NW, BX
    y1 = by                             # top of the column lines up with the top of the binary
    add(box(BX, y1, BW, 80)); add(text(BX + 20, y1 + 36, "S3 bucket", 17, c["text"], 600)); add(text(BX + 20, y1 + 59, "versioned on AWS", 14, c["sub"]))
    add(text(BX + BW / 2, y1 + 106, "or", 14, c["sub"], 400, "middle"))
    add(box(BX, y1 + 124, BW, 80)); add(text(BX + 20, y1 + 160, "Local disk", 17, c["text"], 600)); add(text(BX + 20, y1 + 183, "on the node or a mount", 14, c["sub"]))
    add(arrow(gx0, y1 + 40, gx1, y1 + 40))
    add(text((gx0 + gx1) / 2, y1 + 18, "WAL +", 12, c["sub"], 500, "middle", spacing=0.2))
    add(text((gx0 + gx1) / 2, y1 + 33, "base backups", 12, c["sub"], 500, "middle", spacing=0))
    add(box(BX, y1 + 244, BW, 80, fill="none", dash="5 5"))
    add(text(BX + 20, y1 + 280, "Point-in-time restore", 15, c["text"], 600))
    add(text(BX + 20, y1 + 303, "in place or as a copy", 14, c["sub"]))
    # an optional second server: a dashed box like the restore box, joined to the node by the mesh port
    y2 = y1 + 348
    add(box(BX, y2, BW, 84, fill="none", stroke=c["accent"], dash="5 5"))
    add(text(BX + 20, y2 + 33, "Second server", 17, c["text"], 600))
    add(text(BX + 20, y2 + 56, "replicas and failover", 14, c["sub"]))
    add(darrow(gx0, y2 + 42, gx1, y2 + 42))
    add(text((gx0 + gx1) / 2, y2 + 28, "mesh", 12, c["sub"], 500, "middle", spacing=0.2))
    add(text((gx0 + gx1) / 2, y2 + 66, "TCP 7443", 12, c["sub"], 500, "middle", spacing=0))

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W_} {H_}" width="{W_}" height="{H_}" role="img" aria-label="Supavise architecture">
  <title>Supavise architecture ({theme})</title>
  <desc>Clients (a browser showing Supabase Studio, the Supabase CLI, the MCP server and your apps) reach one Supavise node over HTTPS. The supavise binary is the HTTPS proxy, the Management API, the project lifecycle engine and the backup service. Each project has its own Postgres, Auth and REST; all projects share Supavisor, Realtime, Storage, Edge Runtime and Studio. Backups go to S3 or local disk, and point-in-time restore runs in place or as a copy. An optional second server joins the node over the mesh port for read replicas and failover. Generated by brand/build.py.</desc>
  <rect width="{W_}" height="{H_}" fill="{c["bg"]}"/>
  {chr(10).join("  " + o for o in out).strip()}
</svg>
"""

# ---- README graphics, part two ---------------------------------------------
# Feature grid, "Get started" path cards, badges, heading glyph and footer. Same rules as above: SVG only, no
# webfonts, system font stack, brand color on black (teal) and on light (ink), neutral grays for boxes and body text.
# The grid, the cards and the glyph have a transparent ground so they sit on GitHub's own page color; the footer is
# a solid band like the banner it mirrors.

# Icons are drawn on a 48-unit grid: one 4-unit stroke, square butt caps, mitered joins (the mark has no rounding),
# and one filled accent per icon where it helps. Filled accents carry fill="@", swapped for the color.
ICONS = {
    "dashboard": '<rect x="5" y="7" width="38" height="34"/><path d="M18 7V41"/>'
                 '<path stroke="none" fill="@" d="M25 15h13v7H25z"/><path d="M25 30h13"/>',
    "project":   '<path d="M24 6L42 15L24 24L6 15Z"/><path d="M6 24L24 33L42 24"/><path d="M6 33L24 42L42 33"/>',
    "branch":    '<path d="M14 10V38"/><path d="M34 10V20L14 32"/>'
                 '<path stroke="none" fill="@" d="M9 5h10v10H9zM29 5h10v10H29zM9 33h10v10H9z"/>',
    "backup":    '<path d="M12.7 12.7A16 16 0 1 1 8 24"/><path d="M24 15V24L30 28"/>'
                 '<path stroke="none" fill="@" d="M2 20.5L14 25.5L8 11.5Z"/>',
    "team":      '<circle cx="24" cy="15" r="7"/><path d="M9 41V35L16 28H32L39 35V41Z"/>',
    "key":       '<circle cx="15" cy="24" r="9"/><path d="M24 24H44"/><path d="M34 24V32M41 24V30"/>',
    "shield":    '<path d="M24 5L40 11V24L24 43L8 24V11Z"/><path d="M16 23L22 29L32 18"/>',
    "cloud":     '<path d="M14 37A8 8 0 0 1 12.8 21.2A12 12 0 0 1 35.6 19.2A9 9 0 0 1 35 37Z"/>',
    "chip":      '<rect x="12" y="12" width="24" height="24"/><path stroke="none" fill="@" d="M19 19h10v10H19z"/>'
                 '<path d="M18 4V12M30 4V12M18 36V44M30 36V44M4 18H12M4 30H12M36 18H44M36 30H44"/>',
    "pulse":     '<path d="M4 26H14L19 13L28 37L33 22H44"/>',
    "server":    '<rect x="5" y="7" width="38" height="14"/><rect x="5" y="27" width="38" height="14"/>'
                 '<path stroke="none" fill="@" d="M12 12h4v4h-4zM12 32h4v4h-4z"/><path d="M26 14H36M26 34H36"/>',
    "replica":   '<rect x="4" y="8" width="14" height="32"/><rect x="30" y="8" width="14" height="32"/>'
                 '<path d="M18 24H30"/><path stroke="none" fill="@" d="M8 13h6v6H8z"/>',
    "failover":  '<path d="M6 16H30"/><path stroke="none" fill="@" d="M30 8L44 16L30 24Z"/>'
                 '<path d="M42 32H18"/><path stroke="none" fill="@" d="M18 24L4 32L18 40Z"/>',
    "upgrade":   '<path d="M24 36V14"/><path d="M12 24L24 12L36 24"/><path stroke="none" fill="@" d="M8 38h32v6H8z"/>',
    "bucket":    '<ellipse cx="24" cy="12" rx="16" ry="6"/><path d="M8 12V36A16 6 0 0 0 40 36V12"/>'
                 '<path stroke="none" fill="@" d="M19 24h10v6H19z"/>',
}

def icon(name, x, y, size, color):
    body = ICONS[name].replace('fill="@"', f'fill="{color}"')
    return (f'<g transform="translate({x:g} {y:g}) scale({size / 48:.4f})" fill="none" stroke="{color}" stroke-width="4" '
            f'stroke-linejoin="miter" stroke-linecap="butt">{body}</g>')

FEATURES = [
    ("dashboard", "Dashboard", "The real Supabase Studio, with multiple organizations and projects"),
    ("project", "Every project", "Postgres, Auth, REST, GraphQL, Realtime, Storage, Edge Functions and custom domains"),
    ("chip", "Compute sizes", "Nano to 16XL per project, like hosted, resized from the dashboard"),
    ("branch", "Branching", "Schema-only branches or full copies of your data, for previews and agents"),
    ("backup", "Backups", "Point-in-time restore from the dashboard, including Storage files"),
    ("bucket", "Storage on S3", "Move Storage's files to an S3 bucket in place, with a short pause for writes"),
    ("replica", "Read replicas", "A copy of a project on a second server, with its own API and pooler endpoints"),
    ("failover", "Failover", "Switch a project or the whole server to its replica, by hand or automatically on AWS"),
    ("team", "Teams", "Organizations, roles, invitations, SAML single sign-on and MFA"),
    ("key", "API keys", "Publishable and secret keys, legacy JWT keys and key rotation"),
    ("pulse", "Monitoring", "Health checks, an uptime endpoint, and alerts by email or webhook"),
    ("shield", "Operations", "Automatic HTTPS, security patches and signed updates"),
    ("upgrade", "Upgrades", "One command brings servers and AWS stacks forward from v0.1.x, backed up first"),
    ("cloud", "AWS", "A one-field CloudFormation template, and a second stack for a replica server"),
]

def wrap(t, n):
    import textwrap
    return textwrap.wrap(t, n)

def frame(w, h, title, desc, body, bg=None):
    ground = f'\n  <rect width="{w}" height="{h}" fill="{bg}"/>' if bg else ""
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" role="img" aria-label="{esc(title)}">
  <title>{esc(title)}</title>
  <desc>{esc(desc)} Generated by brand/build.py.</desc>{ground}
  {body}
</svg>
'''

def features_svg(theme):
    c = THEMES[theme]; W_ = 1200; CW, CH, GAP_ = 592, 112, 16
    out = []
    for i, (ic, title, line) in enumerate(FEATURES):
        x = 1 + (i % 2) * (CW + GAP_); y = 1 + (i // 2) * (CH + GAP_)
        out.append(f'<rect x="{x}" y="{y}" width="{CW - 2}" height="{CH - 2}" rx="10" fill="{c["box"]}" stroke="{c["line"]}" stroke-width="1.5"/>')
        out.append(icon(ic, x + 30, y + (CH - 44) / 2, 44, c["accent"]))
        out.append(text(x + 100, y + 44, title, 24, c["text"], 700))
        for j, ln in enumerate(wrap(line, 46)):
            out.append(text(x + 100, y + 71 + j * 23, ln, 17, c["sub"]))
    rows = (len(FEATURES) + 1) // 2
    H_ = 2 + rows * CH + (rows - 1) * GAP_
    desc = "What is included: " + " ".join(f"{t}: {l}." for _, t, l in FEATURES)
    return frame(W_, H_, f"What is included ({theme})", desc, "\n  ".join(out))

PATHS = {
    "server": ("server", "Your server", "Ubuntu 24.04+ or Debian 12+, 4–8 GB of memory", "Run one install command"),
    "aws":    ("cloud", "AWS", "A CloudFormation template with one field", "Create a stack from one file"),
}

def path_svg(theme, key):
    c = THEMES[theme]; ic, title, line, cta = PATHS[key]; W_, H_ = 580, 148
    out = [f'<rect x="1" y="1" width="{W_ - 2}" height="{H_ - 2}" rx="12" fill="{c["box"]}" stroke="{c["accent"]}" stroke-width="2"/>',
           icon(ic, 30, 30, 48, c["accent"]),
           text(106, 54, title, 28, c["text"], 700),
           text(106, 82, line, 18, c["sub"]),
           text(132, 118, cta, 17, c["accent"] if theme == "dark" else c["text"], 600),
           f'<path d="M110 104V118M105 113L110 119L115 113" fill="none" stroke="{c["accent"]}" stroke-width="2"/>']
    return frame(W_, H_, f"{title}: {line}. {cta}", f"Get started on {title}. {line}. {cta}.", "\n  ".join(out))

# Narrow variants for phones. The README picks them with <source media="(max-width: 600px)">. The grid and the cards
# are drawn for a 1200 and a 580 unit wide page: a phone shows the grid at about a quarter of that and each of the two
# side by side cards at 49% of a 340 px column, so their text comes out near 6 px. These are drawn at the size they
# are shown at (a phone column is 340 to 400 px wide, so a unit is about a pixel): the grid is one column of cards, and
# a path card is one column too (icon, title, text and call to action stacked), 200 units wide so that two of them
# still sit side by side at 49% each, as in the wide layout. Smallest text is 15 units.

def features_narrow_svg(theme):
    c = THEMES[theme]; W_, CW, GAP_ = 400, 400, 12
    out = []; y = 1
    for ic, title, line in FEATURES:
        lines = wrap(line, 34)
        ch = max(88, 62 + 21 * len(lines) + 16)
        out.append(f'<rect x="1" y="{y}" width="{CW - 2}" height="{ch - 2}" rx="10" fill="{c["box"]}" stroke="{c["line"]}" stroke-width="1.5"/>')
        out.append(icon(ic, 20, y + (ch - 40) / 2, 40, c["accent"]))
        out.append(text(80, y + 36, title, 21, c["text"], 700))
        for j, ln in enumerate(lines):
            out.append(text(80, y + 62 + j * 21, ln, 15, c["sub"]))
        y += ch + GAP_
    H_ = y - GAP_ + 1
    desc = "What is included: " + " ".join(f"{t}: {l}." for _, t, l in FEATURES)
    return frame(W_, H_, f"What is included ({theme}, narrow)", desc, "\n  ".join(out))

NARROW_PATH_W = 200

def path_narrow_layout(key):
    ic, title, line, cta = PATHS[key]
    return ic, title, wrap(line, 22), wrap(cta, 22)

def path_narrow_height():
    # Both cards are drawn the same height, so that they line up when they sit side by side.
    hs = []
    for key in PATHS:
        _, _, body, cta = path_narrow_layout(key)
        hs.append(112 + 20 * len(body) + 14 + 20 * len(cta) + 18)
    return max(hs)

def path_narrow_svg(theme, key):
    c = THEMES[theme]; W_ = NARROW_PATH_W; H_ = path_narrow_height()
    ic, title, body, cta = path_narrow_layout(key)
    cta_c = c["accent"] if theme == "dark" else c["text"]
    y = 112 + 20 * len(body) + 14
    out = [f'<rect x="1" y="1" width="{W_ - 2}" height="{H_ - 2}" rx="12" fill="{c["box"]}" stroke="{c["accent"]}" stroke-width="2"/>',
           icon(ic, 18, 18, 40, c["accent"]),
           text(18, 92, title, 22, c["text"], 700)]
    for j, ln in enumerate(body):
        out.append(text(18, 118 + j * 20, ln, 15, c["sub"]))
    # The arrow sits left of the call to action, the way it does on the wide card, and spans both lines.
    out.append(f'<path d="M24 {y + 2:g}V{y + 16:g}M19 {y + 11:g}L24 {y + 17:g}L29 {y + 11:g}" fill="none" stroke="{c["accent"]}" stroke-width="2"/>')
    for j, ln in enumerate(cta):
        out.append(text(40, y + 16 + j * 20, ln, 15, cta_c, 600))
    return frame(W_, H_, f"{PATHS[key][1]}: {PATHS[key][2]}. {PATHS[key][3]}", f"Get started on {PATHS[key][1]}. {PATHS[key][2]}. {PATHS[key][3]}.", "\n  ".join(out))

BADGES = [("license", "Apache-2.0", "license", "Apache-2.0"),
          ("platform", "Ubuntu 24.04+ | Debian 12+", "runs on", "Ubuntu 24.04+ | Debian 12+"),
          ("arch", "amd64 | arm64", "arch", "amd64 | arm64"),
          ("docker", "systemd units, no Docker", "runs as", "systemd units, no Docker")]

def badge_svg(label, msg):
    # shields.io picks its text color from the background and prints white on #00e0c4 (about 1.3:1), so the
    # README badges are drawn here: white label on ink, ink message on teal (about 12:1). textLength pins each
    # string to its box whatever face the reader's system substitutes.
    H_ = 22; cw = 6.3
    lw = round(len(label) * cw) ; mw = round(len(msg) * cw)
    lx, mx = 9, 9
    w1, w2 = lw + 2 * lx, mw + 2 * mx; W_ = w1 + w2
    t = lambda x, s, w, fill, wt: (f'<text x="{x:g}" y="15" font-family="{SANS}" font-size="12" font-weight="{wt}" fill="{fill}" '
                                   f'textLength="{w}" lengthAdjust="spacingAndGlyphs">{esc(s)}</text>')
    body = (f'<clipPath id="r"><rect width="{W_}" height="{H_}" rx="4"/></clipPath>'
            f'<g clip-path="url(#r)"><rect width="{w1}" height="{H_}" fill="{INK}"/><rect x="{w1}" width="{w2}" height="{H_}" fill="{BRAND}"/></g>'
            f'<rect x=".5" y=".5" width="{W_ - 1}" height="{H_ - 1}" rx="3.5" fill="none" stroke="#3a3a3a" stroke-opacity=".6"/>'
            + t(lx, label, lw, WHITE, 500) + t(w1 + mx, msg, mw, INK, 700))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W_} {H_}" width="{W_}" height="{H_}" role="img" aria-label="{esc(label)}: {esc(msg)}">
  <title>{esc(label)}: {esc(msg)}</title>
  {body}
</svg>
'''

def glyph_svg(theme):
    # The mark at heading size, with its right gap built in so the heading text can follow it without a space:
    # a space would put a leading hyphen in GitHub's anchor id.
    c = THEMES[theme]; gh = 17; sc = gh / MH; gap = 12
    w = (MW + 2 * MARK_PAD) * sc
    vw, vh = w + gap, (MH + 2 * MARK_PAD) * sc
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {vw:.2f} {vh:.2f}" width="{vw:.2f}" height="{vh:.2f}" aria-hidden="true">
  <title>Supavise mark</title>
  <svg x="0" y="0" width="{w:.2f}" height="{vh:.2f}" viewBox="{VB}"><path fill="{c["mark_c"]}" d="{MARK}"/></svg>
</svg>
'''

def footer_svg(theme, k):
    c = THEMES[theme]; W_, H_ = 1280, 176
    lock_h = 64; lw = lock_h * k["w"] / k["h"]; x0 = 96
    cy = H_ / 2 - 2
    lock = lockup_at(x0 - 20 * lock_h / k["h"] + lw / 2, cy, lock_h, c["mark_c"], c["word_c"], k)
    tx = x0 + lw - 20 * lock_h / k["h"] + 64                # text column, after a divider
    body = (mark_at(W_ - 70, H_ / 2, 300, c["ghost"]) + lock
            + f'<line x1="{tx - 32:g}" y1="{cy - 36:g}" x2="{tx - 32:g}" y2="{cy + 38:g}" stroke="{c["accent"]}" stroke-width="2"/>'
            + text(tx, cy + 2, TAGLINE, 30, c["text"], 600, spacing=-0.3)
            + text(tx, cy + 34, "Not affiliated with Supabase Inc.", 15, c["sub"]))
    return canvas(W_, H_, c["bg"], f"README footer ({theme})", body)

# ---- contact sheet -------------------------------------------------------
def variants_html(k):
    inline = lambda svg: svg.strip()
    surf = lambda bg, body: f'<div class="tile" style="background:{bg}">{body}</div>'
    marks = "".join(surf(bg, inline(mark_svg(c, n))) for bg, c, n in [
        ("#ffffff", INK, "ink on white"), (INK, BRAND, "teal on ink"), (BRAND, INK, "ink on teal"), (INK, WHITE, "white on ink")])
    locks = "".join(surf(bg, inline(lockup_svg(mc, wc, n, k))) for bg, mc, wc, n in [
        ("#ffffff", INK, INK, "ink"), (INK, BRAND, WHITE, "color, for black"), (INK, WHITE, WHITE, "white"), (BRAND, INK, INK, "ink on teal")])
    fav = "".join(f'<div class="fav" style="width:{s}px;height:{s}px">{inline(favicon_svg())}</div>' for s in (16, 32, 64, 128))
    social = "".join(f'<div class="wide">{inline(svg)}</div>' for svg in
                     [avatar_svg(SOCIAL, BLACK, "teal"), avatar_svg(BLACK, SOCIAL, "black")] +
                     list(header_svgs(k).values()) + [og_svg(k), og_svg(k, GH, "GitHub social preview")])
    return f'''<!doctype html><meta charset="utf-8"><title>Supavise brand variants</title>
<style>
body{{font:14px/1.4 system-ui,sans-serif;margin:32px;background:#f4f4f4;color:{INK}}}
h2{{margin:40px 0 12px;font-size:13px;text-transform:uppercase;letter-spacing:.08em}}
.row{{display:flex;flex-wrap:wrap;gap:16px;align-items:flex-start}}
.tile{{padding:32px;border:1px solid #0001;display:flex;align-items:center;justify-content:center}}
.tile svg{{height:72px;width:auto}}
.fav{{display:inline-block}} .fav svg{{width:100%;height:100%}}
.wide{{width:min(560px,100%)}} .wide svg{{width:100%;height:auto;display:block}}
</style>
<h2>Mark</h2><div class="row">{marks}</div>
<h2>Lockup</h2><div class="row">{locks}</div>
<h2>Favicon, 16 / 32 / 64 / 128</h2><div class="row" style="align-items:flex-end">{fav}</div>
<h2>Social: avatars, X headers, link previews</h2><div class="row">{social}</div>
'''

def write(rel, content):
    p = os.path.join(ROOT, rel); os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w").write(content); print("wrote", rel)

if __name__ == "__main__":
    write("brand/mark/supavise-mark.svg", mark_svg(BRAND, "Color"))
    write("brand/mark/supavise-mark-black.svg", mark_svg(INK, "Black"))
    write("brand/mark/supavise-mark-white.svg", mark_svg(WHITE, "White"))
    write("brand/favicon.svg", favicon_svg())
    k = build_lockup()
    write("brand/lockups/supavise-horizontal.svg", lockup_svg(BRAND, WHITE, "Color, for black grounds", k))
    write("brand/lockups/supavise-horizontal-black.svg", lockup_svg(INK, INK, "Black", k))
    write("brand/lockups/supavise-horizontal-white.svg", lockup_svg(WHITE, WHITE, "White", k))
    write("brand/social/avatar-teal.svg", avatar_svg(SOCIAL, BLACK, "teal"))
    write("brand/social/avatar-black.svg", avatar_svg(BLACK, SOCIAL, "black"))
    for name, svg in header_svgs(k).items():
        write(f"brand/social/x-header-{name}.svg", svg)
    write("brand/social/og-image.svg", og_svg(k))
    write("brand/social/github-social-preview.svg", og_svg(k, GH, "GitHub social preview"))
    write("brand/social/apple-touch-icon.svg", apple_touch_svg())
    for theme in THEMES:
        write(f"brand/readme/banner-{theme}.svg", banner_svg(theme, k))
        write(f"brand/readme/architecture-{theme}.svg", arch_svg(theme))
        write(f"brand/readme/features-{theme}.svg", features_svg(theme))
        write(f"brand/readme/features-narrow-{theme}.svg", features_narrow_svg(theme))
        write(f"brand/readme/path-server-{theme}.svg", path_svg(theme, "server"))
        write(f"brand/readme/path-aws-{theme}.svg", path_svg(theme, "aws"))
        write(f"brand/readme/path-server-narrow-{theme}.svg", path_narrow_svg(theme, "server"))
        write(f"brand/readme/path-aws-narrow-{theme}.svg", path_narrow_svg(theme, "aws"))
        write(f"brand/readme/glyph-{theme}.svg", glyph_svg(theme))
        write(f"brand/readme/footer-{theme}.svg", footer_svg(theme, k))
    for slug, _, label, msg in BADGES:
        write(f"brand/readme/badge-{slug}.svg", badge_svg(label, msg))
    write("brand/variants.html", variants_html(k))
    print("mark ink", round(MW), "x", round(MH), "(ratio", round(MW / MH, 2), ") | lockup viewBox", k["w"], k["h"])
