"""Generate every Supavise brand asset from one geometry.

    python3 brand/build.py

Writes brand/mark/*.svg, brand/lockups/*.svg, brand/favicon.svg, brand/social/*.svg and brand/variants.html.
Needs fontTools (pip install fonttools) and network access the first time,
to fetch Manrope (OFL) from the google/fonts repo into a temp dir.

Mark geometry, in a 1000-unit box. Two hooks, each the 180-degree rotation of the other:
  a top bar with a stub down its left side, a bottom bar with a stub up its right side. They are drawn
  upright, then leaned by a shear of tan(LEAN) about the middle, with the stubs widened by sqrt(1+k^2) so every
  stroke measures BAR across. The stubs reach past the middle by OV; each stub's far end is cut on a slant so
  the pockets between the hooks narrow to points a hairline GAP from the opposite bar. Those pockets and the
  channel between them are the mark's negative space: a zigzag, the same structure as a bolt.
"""
import math, os, tempfile, urllib.request
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRAND = "#00e0c4"   # signal teal: the mark on black and dark grounds, and the ground that carries an ink mark
INK = "#0b0b0b"     # the mark on light surfaces, and the black of every brand ground
WHITE = "#ffffff"

# ---- mark ----------------------------------------------------------------
H, BAR, LEAN, W = 680, 160, 20, 800     # height, stroke, lean (degrees), width including the lean
OV, GAP = 40, 80                        # stub overlap past the middle, hairline gap at the pocket tips
MARK_PAD = 10                           # viewBox bleed so the edges are not clipped by anti-aliasing

def hooks(h=H, bar=BAR, deg=LEAN, w=W, ov=OV, g=GAP, top=None, bottom=None):
    k = math.tan(math.radians(deg))
    yc = 500
    yt, yb = yc - h / 2, yc + h / 2
    w0 = w - k * h
    x0, x1 = 500 - w0 / 2, 500 + w0 / 2
    sw = bar * math.sqrt(1 + k * k)
    reach = yb - bar - g
    a = [(x0, yt), (x1, yt), (x1, yt + bar), (x0 + sw, yt + bar), (x0 + sw, yc + ov), (x0, reach)]
    b = [(x1, yb), (x0, yb), (x0, yb - bar), (x1 - sw, yb - bar), (x1 - sw, yc - ov), (x1, 2 * yc - reach)]
    sets = [[(x + (yc - y) * k, y) for x, y in p] for p in (a, b)]
    xs = [x for s in sets for x, _ in s]
    path = " ".join("M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in s) + " Z" for s in sets)
    return path, (min(xs), yt, max(xs), yb)

MARK, BBOX = hooks()
MW, MH = BBOX[2] - BBOX[0], BBOX[3] - BBOX[1]     # ink width and height
VB = f"{BBOX[0]-MARK_PAD:.1f} {BBOX[1]-MARK_PAD:.1f} {MW+2*MARK_PAD:.1f} {MH+2*MARK_PAD:.1f}"

def mark_svg(color, title):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VB}" role="img" aria-label="Supavise mark">
  <title>Supavise mark ({title})</title>
  <desc>Two interlocking hooks leaning 20 degrees. One flat color, no strokes, no gradients. The space between the hooks is a zigzag, like a bolt. Generated by brand/build.py.</desc>
  <path fill="{color}" d="{MARK}"/>
</svg>
'''

# The favicon is the mark at tab size on a rounded teal tile. Width 46 of 64, centered. At 16px the hairline
# gap is about 1px, which is the smallest it holds; below that use the tile alone.
def favicon_svg():
    fw = 46; s = fw / MW
    tx, ty = 32 - (BBOX[0] + MW / 2) * s, 32 - (BBOX[1] + MH / 2) * s
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <title>Supavise</title>
  <!-- Signal teal and ink as literals because an SVG file cannot reach any CSS tokens. A solid tile, not the
       bare mark, so it holds on light and dark tab strips alike. Generated by brand/build.py. -->
  <rect width="64" height="64" rx="14" fill="{BRAND}"/>
  <path fill="{INK}" transform="translate({tx:.3f} {ty:.3f}) scale({s:.5f})" d="{MARK}"/>
</svg>
'''

# ---- wordmark ------------------------------------------------------------
# Manrope ExtraBold, the face the Allocait lockup uses, so the family shares one voice. The mark is the S.
FONT_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/manrope/Manrope%5Bwght%5D.ttf"
TRACK = -70       # -0.035em at 2000 upem, as Allocait
LGAP = 215        # mark's right ink edge to the "u" stem
PAD = 20          # lockup viewBox bleed

def load_font():
    cache = os.path.join(tempfile.gettempdir(), "Manrope-800.ttf")
    if not os.path.exists(cache):
        src = os.path.join(tempfile.gettempdir(), "Manrope[wght].ttf")
        urllib.request.urlretrieve(FONT_URL, src)
        instancer.instantiateVariableFont(TTFont(src), {"wght": 800}).save(cache)
    return TTFont(cache)

def build_lockup():
    f = load_font(); gs = f.getGlyphSet(); cmap = f.getBestCmap()
    cap = f["OS/2"].sCapHeight
    glyphs = [gs[cmap[ord(c)]] for c in "upavise"]
    bs = []
    for g in glyphs:
        bp = BoundsPen(gs); g.draw(bp); bs.append(bp.bounds)
    top = max(cap, max(b[3] for b in bs))              # the i dot clears the cap line
    depth = -min(b[1] for b in bs)                     # the p descender
    base = PAD + top
    s = cap / MH                                       # mark height equals cap height; its edges are flat
    mark_w = MW * s
    x = PAD + mark_w + LGAP - bs[0][0]
    parts = []
    for g, b in zip(glyphs, bs):
        pen = SVGPathPen(gs); g.draw(TransformPen(pen, (1, 0, 0, -1, x, base)))
        parts.append(pen.getCommands()); last = x + b[2]; x += g.width + TRACK
    return dict(s=s, w=round(last + PAD), h=round(base + depth + PAD), word=" ".join(parts), base=base, cap=cap)

def lockup_body(mark_c, word_c, k):
    s = k["s"]
    tx, ty = PAD - BBOX[0] * s, k["base"] - k["cap"] - BBOX[1] * s
    return (f'<path fill="{mark_c}" transform="translate({tx:.3f} {ty:.3f}) scale({s:.5f})" d="{MARK}"/>'
            f'<path fill="{word_c}" d="{k["word"]}"/>')

def lockup_svg(mark_c, word_c, title, k):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {k["w"]} {k["h"]}" role="img" aria-label="Supavise">
  <title>Supavise ({title})</title>
  <desc>Horizontal lockup. The mark is the initial S; "upavise" is Manrope ExtraBold outlined to paths, tracked -3.5%. Mark height is the cap height. Do not re-space. Generated by brand/build.py.</desc>
  {lockup_body(mark_c, word_c, k)}
</svg>
'''

# ---- social --------------------------------------------------------------
SOCIAL, BLACK = BRAND, INK
AVATAR, HEADER, OG, GH = 800, (1500, 500), (1200, 630), (1280, 640)

def nested(x, y, w, h, viewbox, body):
    return f'<svg x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" viewBox="{viewbox}">{body}</svg>'

def mark_at(cx, cy, glyph_h, color):
    # glyph_h is the ink height; the viewBox adds MARK_PAD on each side.
    sc = glyph_h / MH
    w, h = (MW + 2 * MARK_PAD) * sc, (MH + 2 * MARK_PAD) * sc
    return nested(cx - w / 2, cy - h / 2, w, h, VB, f'<path fill="{color}" d="{MARK}"/>')

def lockup_at(cx, cy, lock_h, mark_c, word_c, k):
    lw = lock_h * k["w"] / k["h"]
    return nested(cx - lw / 2, cy - lock_h / 2, lw, lock_h, f'0 0 {k["w"]} {k["h"]}', lockup_body(mark_c, word_c, k))

def canvas(w, h, bg, title, body):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">
  <title>Supavise {title}</title>
  <rect width="{w}" height="{h}" fill="{bg}"/>
  {body}
</svg>
'''

def avatar_svg(bg, fg, title):
    # Mark 56% of the side wide: the avatar crops to a circle on X, LinkedIn, GitHub and Bluesky.
    gh = AVATAR * 0.56 / (MW / MH)
    return canvas(AVATAR, AVATAR, bg, f"avatar ({title})", mark_at(AVATAR / 2, AVATAR / 2, gh, fg))

def apple_touch_svg():
    return canvas(180, 180, BRAND, "apple touch icon", mark_at(90, 90, 124 / (MW / MH), INK))

def header_svgs(k):
    W_, H_ = HEADER
    lock = lambda mc, wc: lockup_at(W_ / 2, H_ / 2, 100, mc, wc, k)
    return {
        # The mark oversized off the right edge, the zigzag in frame.
        "slice": canvas(W_, H_, BLACK, "X header (slice)", mark_at(1330, 210, 700, SOCIAL) + lock(SOCIAL, WHITE)),
        "black": canvas(W_, H_, BLACK, "X header (black)", lock(SOCIAL, WHITE)),
        "teal": canvas(W_, H_, SOCIAL, "X header (teal)", lock(INK, INK)),
    }

def og_svg(k, size=OG, name="link preview"):
    W_, H_ = size
    return canvas(W_, H_, BLACK, name,
                  mark_at(W_ - 190, H_ / 2 - 10, H_ * 0.86, SOCIAL) + lockup_at(W_ * 0.33, H_ / 2, 120, SOCIAL, WHITE, k))

# ---- contact sheet -------------------------------------------------------
def variants_html(k):
    inline = lambda svg: svg.strip()
    surf = lambda bg, body: f'<div class="tile" style="background:{bg}">{body}</div>'
    marks = "".join(surf(bg, inline(mark_svg(c, n))) for bg, c, n in [
        ("#ffffff", INK, "ink on white"), (INK, BRAND, "teal on ink"), (BRAND, INK, "ink on teal"), (INK, WHITE, "white on ink")])
    locks = "".join(surf(bg, inline(lockup_svg(mc, wc, n, k))) for bg, mc, wc, n in [
        ("#ffffff", INK, INK, "ink"), (INK, BRAND, WHITE, "color, for black"), (INK, WHITE, WHITE, "white"), (BRAND, INK, INK, "ink on teal")])
    fav = "".join(f'<div class="fav" style="width:{s}px;height:{s}px">{inline(favicon_svg())}</div>' for s in (16, 32, 64, 128))
    social = "".join(f'<div class="wide">{inline(svg)}</div>' for svg in
                     [avatar_svg(SOCIAL, BLACK, "teal"), avatar_svg(BLACK, SOCIAL, "black")] +
                     list(header_svgs(k).values()) + [og_svg(k), og_svg(k, GH, "GitHub social preview")])
    return f'''<!doctype html><meta charset="utf-8"><title>Supavise brand variants</title>
<style>
body{{font:14px/1.4 system-ui,sans-serif;margin:32px;background:#f4f4f4;color:{INK}}}
h2{{margin:40px 0 12px;font-size:13px;text-transform:uppercase;letter-spacing:.08em}}
.row{{display:flex;flex-wrap:wrap;gap:16px;align-items:flex-start}}
.tile{{padding:32px;border:1px solid #0001;display:flex;align-items:center;justify-content:center}}
.tile svg{{height:72px;width:auto}}
.fav{{display:inline-block}} .fav svg{{width:100%;height:100%}}
.wide{{width:min(560px,100%)}} .wide svg{{width:100%;height:auto;display:block}}
</style>
<h2>Mark</h2><div class="row">{marks}</div>
<h2>Lockup</h2><div class="row">{locks}</div>
<h2>Favicon, 16 / 32 / 64 / 128</h2><div class="row" style="align-items:flex-end">{fav}</div>
<h2>Social: avatars, X headers, link previews</h2><div class="row">{social}</div>
'''

def write(rel, content):
    p = os.path.join(ROOT, rel); os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w").write(content); print("wrote", rel)

if __name__ == "__main__":
    write("brand/mark/supavise-mark.svg", mark_svg(BRAND, "Color"))
    write("brand/mark/supavise-mark-black.svg", mark_svg(INK, "Black"))
    write("brand/mark/supavise-mark-white.svg", mark_svg(WHITE, "White"))
    write("brand/favicon.svg", favicon_svg())
    k = build_lockup()
    write("brand/lockups/supavise-horizontal.svg", lockup_svg(BRAND, WHITE, "Color, for black grounds", k))
    write("brand/lockups/supavise-horizontal-black.svg", lockup_svg(INK, INK, "Black", k))
    write("brand/lockups/supavise-horizontal-white.svg", lockup_svg(WHITE, WHITE, "White", k))
    write("brand/social/avatar-teal.svg", avatar_svg(SOCIAL, BLACK, "teal"))
    write("brand/social/avatar-black.svg", avatar_svg(BLACK, SOCIAL, "black"))
    for name, svg in header_svgs(k).items():
        write(f"brand/social/x-header-{name}.svg", svg)
    write("brand/social/og-image.svg", og_svg(k))
    write("brand/social/github-social-preview.svg", og_svg(k, GH, "GitHub social preview"))
    write("brand/social/apple-touch-icon.svg", apple_touch_svg())
    write("brand/variants.html", variants_html(k))
    print("mark ink", round(MW), "x", round(MH), "(ratio", round(MW / MH, 2), ") | lockup viewBox", k["w"], k["h"])
