"""Generate every Supavise brand asset from one geometry.

    python3 brand/build.py

Writes brand/mark/*.svg, brand/lockups/*.svg, brand/favicon.svg, brand/social/*.svg, brand/readme/*.svg
(the README banner and architecture diagram, each in a dark and a light variant) and brand/variants.html.
Needs fontTools (pip install fonttools) and network access the first time,
to fetch Manrope (OFL) from the google/fonts repo into a temp dir.

Mark geometry, in a 1000-unit box. Two hooks, each the 180-degree rotation of the other:
  a top bar with a stub down its left side, a bottom bar with a stub up its right side. They are drawn
  upright, then leaned by a shear of tan(LEAN) about the middle, with the stubs widened by sqrt(1+k^2) so every
  stroke measures BAR across. The stubs reach past the middle by OV; each stub's far end is cut on a slant so
  the pockets between the hooks narrow to points a hairline GAP from the opposite bar. Those pockets and the
  channel between them are the mark's negative space: a zigzag, the same structure as a bolt.
"""
import math, os, tempfile, urllib.request
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRAND = "#00e0c4"   # signal teal: the mark on black and dark grounds, and the ground that carries an ink mark
INK = "#0b0b0b"     # the mark on light surfaces, and the black of every brand ground
WHITE = "#ffffff"

# ---- mark ----------------------------------------------------------------
H, BAR, LEAN, W = 680, 160, 20, 800     # height, stroke, lean (degrees), width including the lean
OV, GAP = 40, 80                        # stub overlap past the middle, hairline gap at the pocket tips
MARK_PAD = 10                           # viewBox bleed so the edges are not clipped by anti-aliasing

def hooks(h=H, bar=BAR, deg=LEAN, w=W, ov=OV, g=GAP, top=None, bottom=None):
    k = math.tan(math.radians(deg))
    yc = 500
    yt, yb = yc - h / 2, yc + h / 2
    w0 = w - k * h
    x0, x1 = 500 - w0 / 2, 500 + w0 / 2
    sw = bar * math.sqrt(1 + k * k)
    reach = yb - bar - g
    a = [(x0, yt), (x1, yt), (x1, yt + bar), (x0 + sw, yt + bar), (x0 + sw, yc + ov), (x0, reach)]
    b = [(x1, yb), (x0, yb), (x0, yb - bar), (x1 - sw, yb - bar), (x1 - sw, yc - ov), (x1, 2 * yc - reach)]
    sets = [[(x + (yc - y) * k, y) for x, y in p] for p in (a, b)]
    xs = [x for s in sets for x, _ in s]
    path = " ".join("M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in s) + " Z" for s in sets)
    return path, (min(xs), yt, max(xs), yb)

MARK, BBOX = hooks()
MW, MH = BBOX[2] - BBOX[0], BBOX[3] - BBOX[1]     # ink width and height
VB = f"{BBOX[0]-MARK_PAD:.1f} {BBOX[1]-MARK_PAD:.1f} {MW+2*MARK_PAD:.1f} {MH+2*MARK_PAD:.1f}"

def mark_svg(color, title):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VB}" role="img" aria-label="Supavise mark">
  <title>Supavise mark ({title})</title>
  <desc>Two interlocking hooks leaning 20 degrees. One flat color, no strokes, no gradients. The space between the hooks is a zigzag, like a bolt. Generated by brand/build.py.</desc>
  <path fill="{color}" d="{MARK}"/>
</svg>
'''

# The favicon is the mark at tab size on a rounded teal tile. Width 46 of 64, centered. At 16px the hairline
# gap is about 1px, which is the smallest it holds; below that use the tile alone.
def favicon_svg():
    fw = 46; s = fw / MW
    tx, ty = 32 - (BBOX[0] + MW / 2) * s, 32 - (BBOX[1] + MH / 2) * s
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <title>Supavise</title>
  <!-- Signal teal and ink as literals because an SVG file cannot reach any CSS tokens. A solid tile, not the
       bare mark, so it holds on light and dark tab strips alike. Generated by brand/build.py. -->
  <rect width="64" height="64" rx="14" fill="{BRAND}"/>
  <path fill="{INK}" transform="translate({tx:.3f} {ty:.3f}) scale({s:.5f})" d="{MARK}"/>
</svg>
'''

# ---- wordmark ------------------------------------------------------------
# Manrope ExtraBold, the face the Allocait lockup uses, so the family shares one voice. The mark is the S.
FONT_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/manrope/Manrope%5Bwght%5D.ttf"
TRACK = -70       # -0.035em at 2000 upem, as Allocait
LGAP = 215        # mark's right ink edge to the "u" stem
PAD = 20          # lockup viewBox bleed

def load_font():
    cache = os.path.join(tempfile.gettempdir(), "Manrope-800.ttf")
    if not os.path.exists(cache):
        src = os.path.join(tempfile.gettempdir(), "Manrope[wght].ttf")
        urllib.request.urlretrieve(FONT_URL, src)
        instancer.instantiateVariableFont(TTFont(src), {"wght": 800}).save(cache)
    return TTFont(cache)

def build_lockup():
    f = load_font(); gs = f.getGlyphSet(); cmap = f.getBestCmap()
    cap = f["OS/2"].sCapHeight
    glyphs = [gs[cmap[ord(c)]] for c in "upavise"]
    bs = []
    for g in glyphs:
        bp = BoundsPen(gs); g.draw(bp); bs.append(bp.bounds)
    top = max(cap, max(b[3] for b in bs))              # the i dot clears the cap line
    depth = -min(b[1] for b in bs)                     # the p descender
    base = PAD + top
    s = cap / MH                                       # mark height equals cap height; its edges are flat
    mark_w = MW * s
    x = PAD + mark_w + LGAP - bs[0][0]
    parts = []
    for g, b in zip(glyphs, bs):
        pen = SVGPathPen(gs); g.draw(TransformPen(pen, (1, 0, 0, -1, x, base)))
        parts.append(pen.getCommands()); last = x + b[2]; x += g.width + TRACK
    return dict(s=s, w=round(last + PAD), h=round(base + depth + PAD), word=" ".join(parts), base=base, cap=cap)

def lockup_body(mark_c, word_c, k):
    s = k["s"]
    tx, ty = PAD - BBOX[0] * s, k["base"] - k["cap"] - BBOX[1] * s
    return (f'<path fill="{mark_c}" transform="translate({tx:.3f} {ty:.3f}) scale({s:.5f})" d="{MARK}"/>'
            f'<path fill="{word_c}" d="{k["word"]}"/>')

def lockup_svg(mark_c, word_c, title, k):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {k["w"]} {k["h"]}" role="img" aria-label="Supavise">
  <title>Supavise ({title})</title>
  <desc>Horizontal lockup. The mark is the initial S; "upavise" is Manrope ExtraBold outlined to paths, tracked -3.5%. Mark height is the cap height. Do not re-space. Generated by brand/build.py.</desc>
  {lockup_body(mark_c, word_c, k)}
</svg>
'''

# ---- social --------------------------------------------------------------
SOCIAL, BLACK = BRAND, INK
AVATAR, HEADER, OG, GH = 800, (1500, 500), (1200, 630), (1280, 640)

def nested(x, y, w, h, viewbox, body):
    return f'<svg x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" viewBox="{viewbox}">{body}</svg>'

def mark_at(cx, cy, glyph_h, color):
    # glyph_h is the ink height; the viewBox adds MARK_PAD on each side.
    sc = glyph_h / MH
    w, h = (MW + 2 * MARK_PAD) * sc, (MH + 2 * MARK_PAD) * sc
    return nested(cx - w / 2, cy - h / 2, w, h, VB, f'<path fill="{color}" d="{MARK}"/>')

def lockup_at(cx, cy, lock_h, mark_c, word_c, k):
    lw = lock_h * k["w"] / k["h"]
    return nested(cx - lw / 2, cy - lock_h / 2, lw, lock_h, f'0 0 {k["w"]} {k["h"]}', lockup_body(mark_c, word_c, k))

def canvas(w, h, bg, title, body):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">
  <title>Supavise {title}</title>
  <rect width="{w}" height="{h}" fill="{bg}"/>
  {body}
</svg>
'''

def avatar_svg(bg, fg, title):
    # Mark 56% of the side wide: the avatar crops to a circle on X, LinkedIn, GitHub and Bluesky.
    gh = AVATAR * 0.56 / (MW / MH)
    return canvas(AVATAR, AVATAR, bg, f"avatar ({title})", mark_at(AVATAR / 2, AVATAR / 2, gh, fg))

def apple_touch_svg():
    return canvas(180, 180, BRAND, "apple touch icon", mark_at(90, 90, 124 / (MW / MH), INK))

def header_svgs(k):
    W_, H_ = HEADER
    lock = lambda mc, wc: lockup_at(W_ / 2, H_ / 2, 100, mc, wc, k)
    return {
        # The mark oversized off the right edge, the zigzag in frame.
        "slice": canvas(W_, H_, BLACK, "X header (slice)", mark_at(1330, 210, 700, SOCIAL) + lock(SOCIAL, WHITE)),
        "black": canvas(W_, H_, BLACK, "X header (black)", lock(SOCIAL, WHITE)),
        "teal": canvas(W_, H_, SOCIAL, "X header (teal)", lock(INK, INK)),
    }

def og_svg(k, size=OG, name="link preview"):
    W_, H_ = size
    return canvas(W_, H_, BLACK, name,
                  mark_at(W_ - 190, H_ / 2 - 10, H_ * 0.86, SOCIAL) + lockup_at(W_ * 0.33, H_ / 2, 120, SOCIAL, WHITE, k))

# ---- README graphics -----------------------------------------------------
# Banner and architecture diagram, each in a dark and a light variant for <picture>. GitHub shows SVG through
# <img>, so there are no webfonts, external references or foreignObject: the lockup is outlined paths and every
# other word is live text in a system font stack. Brand color is teal on black and ink on light; boxes and
# secondary text are neutral grays, picked to keep at least 4.5:1 against their ground.
SANS = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, Helvetica, Arial, sans-serif"
MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
TAGLINE = "Many Supabase projects. One server."
SUBLINE = "Self-hosted and open source. Not affiliated with Supabase Inc."

THEMES = {
    "dark":  dict(bg=BLACK, accent=BRAND, word=WHITE, text=WHITE, sub="#a3a3a3", box="#151515", line="#3a3a3a",
                  mark_c=BRAND, word_c=WHITE, ghost="#141414", onaccent=INK),
    "light": dict(bg=WHITE, accent=INK, word=INK, text=INK, sub="#595959", box="#f4f4f4", line="#c9c9c9",
                  mark_c=INK, word_c=INK, ghost="#f3f3f3", onaccent=WHITE),
}

def esc(t):
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def text(x, y, t, size, fill, weight=400, anchor="start", family=SANS, spacing=None):
    ls = f' letter-spacing="{spacing}"' if spacing is not None else ""
    return (f'<text x="{x:g}" y="{y:g}" font-family="{family}" font-size="{size:g}" font-weight="{weight}" '
            f'fill="{fill}" text-anchor="{anchor}"{ls}>{esc(t)}</text>')

def banner_svg(theme, k):
    c = THEMES[theme]; W_, H_ = 1280, 320
    lock_h = 84; lw = lock_h * k["w"] / k["h"]
    x0 = 96; top = 70
    body = (mark_at(W_ - 70, H_ / 2, 400, c["ghost"])
            + lockup_at(x0 - 20 * lock_h / k["h"] + lw / 2, top + lock_h / 2, lock_h, c["mark_c"], c["word_c"], k)
            + text(x0, top + lock_h + 54, TAGLINE, 34, c["text"], 600, spacing=-0.3)
            + text(x0, top + lock_h + 90, SUBLINE, 18, c["sub"]))
    return canvas(W_, H_, c["bg"], f"README banner ({theme})", body)

def arch_svg(theme):
    c = THEMES[theme]; W_, H_ = 1200, 590
    out = []
    add = out.append
    SW = 1.5                                   # one stroke width for every box and line
    def box(x, y, w, h, fill=None, stroke=None, sw=SW, rx=10, dash=None):
        d = f' stroke-dasharray="{dash}"' if dash else ""
        return (f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="{rx}" fill="{fill or c["box"]}" '
                f'stroke="{stroke or c["line"]}" stroke-width="{sw}"{d}/>')
    def label(x, y, t, anchor="start"):
        return text(x, y, t, 13, c["sub"], 700, anchor, spacing=1.4)
    def arrow(x1, y1, x2, y2, color=None):
        col = color or c["accent"]
        dx = 1 if x2 > x1 else 0; dy = 1 if y2 > y1 else 0
        if dx:
            head = f'{x2:g},{y2:g} {x2-9:g},{y2-5:g} {x2-9:g},{y2+5:g}'; x2 -= 8
        else:
            head = f'{x2:g},{y2:g} {x2-5:g},{y2-9:g} {x2+5:g},{y2-9:g}'; y2 -= 8
        return (f'<line x1="{x1:g}" y1="{y1:g}" x2="{x2:g}" y2="{y2:g}" stroke="{col}" stroke-width="{SW}"/>'
                f'<polygon points="{head}" fill="{col}"/>')
    def darrow(x1, y1, x2, y2):                 # arrowheads at both ends, for request and response traffic
        return arrow(x1, y1, x2, y2) + arrow(x2, y2, x1, y1)

    CX, CW = 24, 192                    # clients column
    NX, NW = 296, 584                   # node container
    BX, BW = 976, 200                   # backups column
    TOP, BOT = 80, 550

    # column labels
    add(label(CX, 52, "CLIENTS")); add(label(NX, 52, "SUPAVISE NODE")); add(text(NX + NW, 52, "one Linux server", 13, c["sub"], 400, "end"))
    add(label(BX, 52, "BACKUPS"))

    # clients
    clients = [("Supabase Studio", "the dashboard"), ("Supabase CLI", "link, push, deploy"),
               ("MCP server", "AI assistants"), ("Your apps", "supabase-js")]
    ch, cg = 80, 24
    y0 = (TOP + BOT) / 2 - (4 * ch + 3 * cg) / 2
    for i, (t, sub) in enumerate(clients):
        y = y0 + i * (ch + cg)
        add(box(CX, y, CW, ch))
        add(text(CX + 20, y + 36, t, 17, c["text"], 600))
        add(text(CX + 20, y + 59, sub, 14, c["sub"]))
    # arrows from the clients into the node: one bus, so the lines do not fan out
    mid = (TOP + BOT) / 2
    bus = CX + CW + 18
    ys = [y0 + i * (ch + cg) + ch / 2 for i in range(4)]
    for y in ys:
        add(f'<line x1="{CX+CW:g}" y1="{y:g}" x2="{bus:g}" y2="{y:g}" stroke="{c["accent"]}" stroke-width="{SW}"/>')
    add(f'<line x1="{bus:g}" y1="{ys[0]:g}" x2="{bus:g}" y2="{ys[-1]:g}" stroke="{c["accent"]}" stroke-width="{SW}"/>')
    add(arrow(bus, mid, NX, mid))
    add(text((bus + NX) / 2, mid - 10, "HTTPS", 12, c["sub"], 500, "middle", spacing=0.4))

    # node container
    add(box(NX, TOP, NW, BOT - TOP, fill="none", stroke=c["accent"], sw=SW, rx=14))
    ix, iw = NX + 24, NW - 48

    # the supavise binary
    by, bh = TOP + 24, 148
    add(box(ix, by, iw, bh, sw=2, stroke=c["accent"]))
    add(mark_at(ix + 36, by + 30, 18, c["accent"]))
    add(text(ix + 58, by + 37, "supavise", 19, c["text"], 700, family=MONO))
    add(text(ix + iw - 20, by + 36, "one Go binary", 14, c["sub"], 400, "end"))
    chips = [("HTTPS", "proxy"), ("Management", "API"), ("Project", "lifecycle"), ("Backup", "service")]
    gap = 12; cw_ = (iw - 40 - 3 * gap) / 4
    for i, (a, b) in enumerate(chips):
        x = ix + 20 + i * (cw_ + gap); y = by + 64
        add(box(x, y, cw_, 64, fill=c["bg"], rx=8))
        add(text(x + cw_ / 2, y + 28, a, 15, c["text"], 600, "middle"))
        add(text(x + cw_ / 2, y + 48, b, 15, c["text"], 600, "middle"))

    # per-project services
    py = by + bh + 44
    add(arrow(NX + NW / 2, by + bh, NX + NW / 2, py - 10, c["accent"]))
    add(label(ix, py + 8, "PER PROJECT"))
    pw = (iw - 2 * 16) / 3; ph = 118
    for i, name in enumerate("ABC"):
        x = ix + i * (pw + 16); y = py + 22
        add(box(x, y, pw, ph))
        add(text(x + 18, y + 31, f"Project {name}", 16, c["text"], 600))
        for j, svc in enumerate(["Postgres", "Auth", "REST"]):
            yy = y + 56 + j * 24
            add(f'<rect x="{x+18:g}" y="{yy-8:g}" width="8" height="8" fill="{c["accent"]}"/>')
            add(text(x + 36, yy, svc, 14, c["sub"]))

    # shared services
    sy = py + 22 + ph + 28
    add(label(ix, sy + 6, "SHARED BY ALL PROJECTS"))
    shared = ["Supavisor", "Realtime", "Storage", "Edge Runtime", "Studio"]
    sg = 10; sw_ = (iw - 4 * sg) / 5
    for i, s_ in enumerate(shared):
        x = ix + i * (sw_ + sg); y = sy + 18
        add(box(x, y, sw_, 44, rx=8))
        add(text(x + sw_ / 2, y + 27, s_, 14, c["text"], 600, "middle"))

    # backups
    gx0, gx1 = NX + NW, BX
    y1 = by                             # top of the column lines up with the top of the binary
    add(box(BX, y1, BW, 80)); add(text(BX + 20, y1 + 36, "S3 bucket", 17, c["text"], 600)); add(text(BX + 20, y1 + 59, "versioned on AWS", 14, c["sub"]))
    add(text(BX + BW / 2, y1 + 106, "or", 14, c["sub"], 400, "middle"))
    add(box(BX, y1 + 124, BW, 80)); add(text(BX + 20, y1 + 160, "Local disk", 17, c["text"], 600)); add(text(BX + 20, y1 + 183, "on the node or a mount", 14, c["sub"]))
    add(arrow(gx0, y1 + 40, gx1, y1 + 40))
    add(text((gx0 + gx1) / 2, y1 + 18, "WAL +", 12, c["sub"], 500, "middle", spacing=0.2))
    add(text((gx0 + gx1) / 2, y1 + 33, "base backups", 12, c["sub"], 500, "middle", spacing=0))
    add(box(BX, y1 + 244, BW, 88, fill="none", dash="5 5"))
    add(text(BX + 20, y1 + 277, "Point-in-time restore", 15, c["text"], 600))
    add(text(BX + 20, y1 + 303, "supavise backups restore", 11.5, c["sub"], 400, family=MONO))

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W_} {H_}" width="{W_}" height="{H_}" role="img" aria-label="Supavise architecture">
  <title>Supavise architecture ({theme})</title>
  <desc>Clients (Supabase Studio, the Supabase CLI, the MCP server and your apps) reach one Supavise node over HTTPS. The supavise binary is the HTTPS proxy, the Management API, the project lifecycle engine and the backup service. Each project has its own Postgres, Auth and REST; all projects share Supavisor, Realtime, Storage, Edge Runtime and Studio. Backups go to S3 or local disk. Generated by brand/build.py.</desc>
  <rect width="{W_}" height="{H_}" fill="{c["bg"]}"/>
  {chr(10).join("  " + o for o in out).strip()}
</svg>
"""

# ---- contact sheet -------------------------------------------------------
def variants_html(k):
    inline = lambda svg: svg.strip()
    surf = lambda bg, body: f'<div class="tile" style="background:{bg}">{body}</div>'
    marks = "".join(surf(bg, inline(mark_svg(c, n))) for bg, c, n in [
        ("#ffffff", INK, "ink on white"), (INK, BRAND, "teal on ink"), (BRAND, INK, "ink on teal"), (INK, WHITE, "white on ink")])
    locks = "".join(surf(bg, inline(lockup_svg(mc, wc, n, k))) for bg, mc, wc, n in [
        ("#ffffff", INK, INK, "ink"), (INK, BRAND, WHITE, "color, for black"), (INK, WHITE, WHITE, "white"), (BRAND, INK, INK, "ink on teal")])
    fav = "".join(f'<div class="fav" style="width:{s}px;height:{s}px">{inline(favicon_svg())}</div>' for s in (16, 32, 64, 128))
    social = "".join(f'<div class="wide">{inline(svg)}</div>' for svg in
                     [avatar_svg(SOCIAL, BLACK, "teal"), avatar_svg(BLACK, SOCIAL, "black")] +
                     list(header_svgs(k).values()) + [og_svg(k), og_svg(k, GH, "GitHub social preview")])
    return f'''<!doctype html><meta charset="utf-8"><title>Supavise brand variants</title>
<style>
body{{font:14px/1.4 system-ui,sans-serif;margin:32px;background:#f4f4f4;color:{INK}}}
h2{{margin:40px 0 12px;font-size:13px;text-transform:uppercase;letter-spacing:.08em}}
.row{{display:flex;flex-wrap:wrap;gap:16px;align-items:flex-start}}
.tile{{padding:32px;border:1px solid #0001;display:flex;align-items:center;justify-content:center}}
.tile svg{{height:72px;width:auto}}
.fav{{display:inline-block}} .fav svg{{width:100%;height:100%}}
.wide{{width:min(560px,100%)}} .wide svg{{width:100%;height:auto;display:block}}
</style>
<h2>Mark</h2><div class="row">{marks}</div>
<h2>Lockup</h2><div class="row">{locks}</div>
<h2>Favicon, 16 / 32 / 64 / 128</h2><div class="row" style="align-items:flex-end">{fav}</div>
<h2>Social: avatars, X headers, link previews</h2><div class="row">{social}</div>
'''

def write(rel, content):
    p = os.path.join(ROOT, rel); os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w").write(content); print("wrote", rel)

if __name__ == "__main__":
    write("brand/mark/supavise-mark.svg", mark_svg(BRAND, "Color"))
    write("brand/mark/supavise-mark-black.svg", mark_svg(INK, "Black"))
    write("brand/mark/supavise-mark-white.svg", mark_svg(WHITE, "White"))
    write("brand/favicon.svg", favicon_svg())
    k = build_lockup()
    write("brand/lockups/supavise-horizontal.svg", lockup_svg(BRAND, WHITE, "Color, for black grounds", k))
    write("brand/lockups/supavise-horizontal-black.svg", lockup_svg(INK, INK, "Black", k))
    write("brand/lockups/supavise-horizontal-white.svg", lockup_svg(WHITE, WHITE, "White", k))
    write("brand/social/avatar-teal.svg", avatar_svg(SOCIAL, BLACK, "teal"))
    write("brand/social/avatar-black.svg", avatar_svg(BLACK, SOCIAL, "black"))
    for name, svg in header_svgs(k).items():
        write(f"brand/social/x-header-{name}.svg", svg)
    write("brand/social/og-image.svg", og_svg(k))
    write("brand/social/github-social-preview.svg", og_svg(k, GH, "GitHub social preview"))
    write("brand/social/apple-touch-icon.svg", apple_touch_svg())
    for theme in THEMES:
        write(f"brand/readme/banner-{theme}.svg", banner_svg(theme, k))
        write(f"brand/readme/architecture-{theme}.svg", arch_svg(theme))
    write("brand/variants.html", variants_html(k))
    print("mark ink", round(MW), "x", round(MH), "(ratio", round(MW / MH, 2), ") | lockup viewBox", k["w"], k["h"])
