// Package oauth is the OAuth 2.1 authorization server of the Management API: the apps (clients),
// authorization requests, grants and tokens behind "Connect > MCP", the Supabase CLI's OAuth
// sign-in and the organization's OAuth Apps page. The HTTP surface lives in internal/api
// (oauth_*.go, mcp.go); this package holds the rules and the stores, so the HTTP layer, the
// operator CLI and the tests share one implementation.
//
// # Vocabulary
//
//   - App: a registered client. A dynamic app registers itself (RFC 7591) and belongs to nobody;
//     a manual app is published by an organization's Owner or Administrator and has client secrets.
//     The app's id is the OAuth client_id (a UUID).
//   - Authorization: one pending request, created by GET /v1/oauth/authorize. Its id is the
//     auth_id that Studio's consent page carries. Approval stores the SHA-256 of a one-time code
//     on it; redemption turns it into a Grant.
//   - Grant: (app, user, organization, scopes, resource). The authority a client holds. It is the
//     unit of revocation. Effective scopes at use are the grant's scopes intersected with the
//     app's current scopes, so narrowing an app takes effect at once.
//   - Token: an access token (sbp_oauth_, one hour) or a refresh token (sbr_, 90 days, rotated on
//     every use). Both belong to a grant.
//
// # Layers
//
//   - types.go, errors.go, scopes.go, urls.go: the vocabulary, limits, errors, scope sets and URL
//     helpers. Pure; no I/O.
//   - authority.go: Authority, the method set of Service as the HTTP layer and the CLI see it, with
//     its request and result types. Tests in other packages fake this interface (embed it in a
//     struct and override the methods the test needs).
//   - store.go: Store, what the Service needs from persistence, including the two transactional
//     methods (WithCode and RotateRefresh). Implemented by PGStore (store_pg.go) and MemoryStore
//     (store_mem.go); both run the same contract tests (storetest).
//   - service.go and the files beside it: Service, the rules. It implements Authority over a Store.
//
// # Rules every layer keeps
//
//   - A secret (access token, refresh token, authorization code, client secret) is shown once, to
//     its owner, and stored as its SHA-256. It never appears in a log line, an audit event, an alert, an
//     error message or a URL the server builds except the redirect that delivers a code.
//   - The state and code_challenge of an authorization request are never logged or audited.
//   - Every time comparison uses the Service's clock (Service.Now), never time.Now, so tests drive
//     expiry and the refresh grace window with a fake clock.
//   - Identifiers that the protocol exposes (app ids, client secret ids, auth_ids) are UUID v4 from
//     crypto/rand, generated by the Service. The Store never invents them. Grant and token ids are
//     the database's identity values; the Store assigns them.
//   - A Store method that reports a missing row returns ErrNotFound (wrapped or not); callers test
//     with errors.Is.
//
// # Errors and the HTTP status the API layer gives them
//
// The Service returns the sentinel errors of errors.go, *Error (an RFC 6749 error with its code),
// or *RedirectError (an authorization error that goes back to the client through its redirect URI).
// Anything else is an internal error and becomes a 500 with a generic message.
//
//	ErrNotFound                       404
//	ErrAlreadyDecided                 409   an authorization that was approved or declined already
//	ErrExpired                        410   an authorization past its expires_at
//	ErrOrgMismatch                    403   approve with an organization other than the requested hint
//	ErrUnknownClient                  422   authorize page: no such app (no redirect)
//	ErrInvalidRedirectURI             400   authorize page: redirect_uri is not registered (no redirect)
//	ErrLimit                          429   a cap of the plan (apps, pending requests); Retry-After
//	ErrInvalid                        400   the organization apps API refuses the input; the message is safe to show
//	ErrNotAdmitted, ErrNotMember      only Service.Admit returns them; the Service turns them into invalid_grant
//	*Error                            Error.Status (400, 401 for invalid_client, 500 for server_error)
//	*RedirectError                    302 to RedirectURI with error, error_description, state and iss
//
// # Concurrency
//
// A Service is safe for concurrent use. A Store is too; WithCode and RotateRefresh serialize the
// callers that contend for one row.
package oauth
