// PostgREST behind /rest/v1 (and pg_graphql behind /graphql/v1), through supabase-js: a table
// created with the Management API's SQL endpoint, CRUD, filters, RPC, and row level security
// allowing and denying by role.
import assert from 'node:assert/strict'
import { before, describe, test } from 'node:test'
import { client, keys, kinds, makeUser, projects, signedIn, sql, waitForRest } from './lib.mjs'

const p = projects.a

before(async () => {
  await sql(p, `
    drop table if exists public.conf_todos cascade;
    create table public.conf_todos (
      id bigint generated by default as identity primary key,
      owner uuid not null default auth.uid(),
      title text not null,
      done boolean not null default false,
      tags text[] not null default '{}'
    );
    alter table public.conf_todos enable row level security;
    create policy owner_select on public.conf_todos for select to authenticated using (owner = (select auth.uid()));
    create policy owner_insert on public.conf_todos for insert to authenticated with check (owner = (select auth.uid()));
    create policy owner_update on public.conf_todos for update to authenticated using (owner = (select auth.uid())) with check (owner = (select auth.uid()));
    create policy owner_delete on public.conf_todos for delete to authenticated using (owner = (select auth.uid()));
    create policy public_done on public.conf_todos for select to anon using (done);
    grant select on public.conf_todos to anon;
    grant select, insert, update, delete on public.conf_todos to authenticated;
    grant all on public.conf_todos to service_role;
    create or replace function public.conf_add(a int, b int) returns int language sql immutable as 'select a + b';
    create or replace function public.conf_my_todos() returns setof public.conf_todos language sql stable as 'select * from public.conf_todos';
    notify pgrst, 'reload schema';
  `)
  await waitForRest(p, keys.a.secret, 'conf_todos')
})

for (const kind of kinds(keys.a)) {
  describe(`PostgREST with the ${kind.label}`, () => {
    const admin = client(p, kind.admin)
    const anon = client(p, kind.anon)
    let u1, u2, c1, c2
    const ids = {}

    before(async () => {
      await admin.from('conf_todos').delete().gte('id', 0)
      u1 = await makeUser(admin, `pg1-${kind.tag}`)
      u2 = await makeUser(admin, `pg2-${kind.tag}`)
      c1 = await signedIn(p, kind.anon, u1)
      c2 = await signedIn(p, kind.anon, u2)
    })

    test('the anon role cannot insert', async () => {
      const { error } = await anon.from('conf_todos').insert({ title: 'nope', owner: u1.id })
      assert.ok(error)
      assert.equal(error.code, '42501')
    })

    test('a user inserts rows and gets them back', async () => {
      const { data, error } = await c1.from('conf_todos').insert([{ title: 'a' }, { title: 'b', done: true }, { title: 'c', tags: ['x', 'y'] }], { defaultToNull: false }).select()
      assert.ifError(error)
      assert.equal(data.length, 3)
      assert.ok(data.every((r) => r.owner === u1.id), 'owner defaults to auth.uid()')
      for (const r of data) ids[r.title] = r.id
    })

    test('row level security: a user sees only their rows, anon only done rows, the secret key all', async () => {
      const mine = await c1.from('conf_todos').select()
      assert.ifError(mine.error)
      assert.equal(mine.data.length, 3)
      const theirs = await c2.from('conf_todos').select()
      assert.ifError(theirs.error)
      assert.equal(theirs.data.length, 0)
      const pub = await anon.from('conf_todos').select()
      assert.ifError(pub.error)
      assert.deepEqual(pub.data.map((r) => r.title), ['b'])
      const all = await admin.from('conf_todos').select()
      assert.ifError(all.error)
      assert.equal(all.data.length, 3)
    })

    test('row level security: another user cannot update, delete or insert as the owner', async () => {
      const upd = await c2.from('conf_todos').update({ title: 'hacked' }).eq('id', ids.a).select()
      assert.ifError(upd.error)
      assert.equal(upd.data.length, 0, 'the row is invisible to the other user')
      const del = await c2.from('conf_todos').delete().eq('id', ids.a).select()
      assert.ifError(del.error)
      assert.equal(del.data.length, 0)
      const ins = await c2.from('conf_todos').insert({ title: 'forged', owner: u1.id })
      assert.equal(ins.error?.code, '42501')
      const check = await admin.from('conf_todos').select('title').eq('id', ids.a).single()
      assert.equal(check.data.title, 'a', 'the row is unchanged')
    })

    test('filters, ordering, paging and counts', async () => {
      const t = () => c1.from('conf_todos').select('title')
      const titles = (r) => {
        assert.ifError(r.error)
        return r.data.map((x) => x.title).sort()
      }
      assert.deepEqual(titles(await t().eq('done', true)), ['b'])
      assert.deepEqual(titles(await t().neq('title', 'a')), ['b', 'c'])
      assert.deepEqual(titles(await t().gt('id', ids.a)), ['b', 'c'])
      assert.deepEqual(titles(await t().in('title', ['a', 'c'])), ['a', 'c'])
      assert.deepEqual(titles(await t().like('title', 'a%')), ['a'])
      assert.deepEqual(titles(await t().ilike('title', 'B')), ['b'])
      assert.deepEqual(titles(await t().is('done', false)), ['a', 'c'])
      assert.deepEqual(titles(await t().contains('tags', ['x'])), ['c'])
      assert.deepEqual(titles(await t().or('title.eq.a,done.eq.true')), ['a', 'b'])
      assert.deepEqual(titles(await t().not('title', 'eq', 'a')), ['b', 'c'])
      const ordered = await t().order('title', { ascending: false }).limit(1)
      assert.deepEqual(ordered.data, [{ title: 'c' }])
      const paged = await t().order('title').range(1, 2)
      assert.deepEqual(paged.data.map((x) => x.title), ['b', 'c'])
      const count = await c1.from('conf_todos').select('*', { count: 'exact', head: true })
      assert.ifError(count.error)
      assert.equal(count.count, 3)
      assert.equal(count.data, null)
    })

    test('single and maybeSingle', async () => {
      const one = await c1.from('conf_todos').select('title').eq('title', 'a').single()
      assert.deepEqual(one.data, { title: 'a' })
      const none = await c1.from('conf_todos').select().eq('title', 'zzz').single()
      assert.equal(none.error?.code, 'PGRST116')
      const maybe = await c1.from('conf_todos').select().eq('title', 'zzz').maybeSingle()
      assert.ifError(maybe.error)
      assert.equal(maybe.data, null)
    })

    test('update, upsert and delete return the rows they touched', async () => {
      const upd = await c1.from('conf_todos').update({ title: 'a2' }).eq('id', ids.a).select()
      assert.ifError(upd.error)
      assert.deepEqual(upd.data.map((r) => r.title), ['a2'])
      const ups = await c1.from('conf_todos').upsert({ id: ids.a, title: 'a3' }, { onConflict: 'id' }).select()
      assert.ifError(ups.error)
      assert.equal(ups.data[0].title, 'a3')
      const del = await c1.from('conf_todos').delete().eq('id', ids.c).select()
      assert.ifError(del.error)
      assert.deepEqual(del.data.map((r) => r.title), ['c'])
      const left = await c1.from('conf_todos').select('*', { count: 'exact', head: true })
      assert.equal(left.count, 2)
    })

    test('rpc: a plain function, GET, a function under row level security, a missing one', async () => {
      const add = await anon.rpc('conf_add', { a: 2, b: 3 })
      assert.ifError(add.error)
      assert.equal(add.data, 5)
      const get = await anon.rpc('conf_add', { a: 1, b: 1 }, { get: true })
      assert.equal(get.data, 2)
      const mine = await c1.rpc('conf_my_todos')
      assert.equal(mine.data.length, 2)
      const theirs = await c2.rpc('conf_my_todos')
      assert.equal(theirs.data.length, 0, 'a security invoker function obeys row level security')
      const missing = await anon.rpc('conf_nothing_like_this')
      assert.equal(missing.error?.code, 'PGRST202')
    })

    test('a request without a key or with a wrong key is refused', async () => {
      const none = await fetch(`${p.url}/rest/v1/conf_todos?select=id`)
      assert.equal(none.status, 401)
      const wrong = await fetch(`${p.url}/rest/v1/conf_todos?select=id`, { headers: { apikey: 'sb_publishable_wrong' } })
      assert.equal(wrong.status, 401)
    })

    test('GraphQL answers at /graphql/v1', async () => {
      const r = await fetch(`${p.url}/graphql/v1`, {
        method: 'POST',
        headers: { apikey: kind.anon, Authorization: `Bearer ${kind.anon}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: '{ __typename }' }),
      })
      const text = await r.text()
      assert.equal(r.status, 200, text)
      assert.equal(JSON.parse(text).data?.__typename, 'Query', text)
    })
  })
}

describe('the keys of one project do not open another', () => {
  test('the publishable key of project A is refused by project B', async () => {
    const r = await fetch(`${projects.b.url}/rest/v1/`, { headers: { apikey: keys.a.publishable } })
    assert.equal(r.status, 401)
    const legacy = await fetch(`${projects.b.url}/rest/v1/`, { headers: { apikey: keys.a.anon, Authorization: `Bearer ${keys.a.anon}` } })
    assert.equal(legacy.status, 401)
  })
})
