// Realtime behind /realtime/v1, through supabase-js: postgres_changes (an insert event),
// broadcast between two clients, and presence (sync, join and leave).
import assert from 'node:assert/strict'
import { after, before, describe, test } from 'node:test'
import { client, keys, kinds, projects, sleep, sql, suffix, waitFor, withTimeout } from './lib.mjs'

const p = projects.a

before(async () => {
  await sql(p, `
    drop table if exists public.conf_rt cascade;
    create table public.conf_rt (id bigint generated by default as identity primary key, msg text not null);
    grant select on public.conf_rt to anon, authenticated;
    grant all on public.conf_rt to service_role;
    alter publication supabase_realtime add table public.conf_rt;
    notify pgrst, 'reload schema';
  `)
})

// subscribe resolves when the channel is joined.
function subscribe(channel) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(`channel ${channel.topic} was not joined within 30 s`)), 30_000)
    channel.subscribe((status, err) => {
      if (status === 'SUBSCRIBED') {
        clearTimeout(timer)
        resolve()
      } else if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT') {
        clearTimeout(timer)
        reject(err ?? new Error(`channel ${channel.topic}: ${status}`))
      }
    })
  })
}

for (const kind of kinds(keys.a)) {
  describe(`Realtime with the ${kind.label}`, () => {
    const a = client(p, kind.anon)
    const b = client(p, kind.anon)
    const admin = client(p, kind.admin)
    const room = `room-${kind.tag}-${suffix}`

    after(async () => {
      await a.removeAllChannels()
      await b.removeAllChannels()
    })

    test('postgres_changes delivers an insert', async () => {
      const marker = `insert-${kind.tag}-${suffix}`
      let event
      const ch = a.channel(`db-${kind.tag}-${suffix}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'conf_rt' }, (payload) => {
        if (payload.new?.msg === marker) event = payload
      })
      await subscribe(ch)
      // The replication slot of the tenant needs a moment after the join: insert until the event arrives.
      await waitFor('the insert event', async () => {
        const { error } = await admin.from('conf_rt').insert({ msg: marker })
        assert.ifError(error)
        await sleep(1500)
        return event
      }, { timeout: 45_000, interval: 0 })
      assert.equal(event.eventType, 'INSERT')
      assert.equal(event.schema, 'public')
      assert.equal(event.table, 'conf_rt')
      assert.equal(event.new.msg, marker)
      await a.removeChannel(ch)
    })

    test('broadcast reaches another client', async () => {
      const rx = a.channel(room, { config: { broadcast: { self: false } } })
      const got = new Promise((resolve) => rx.on('broadcast', { event: 'ping' }, resolve))
      await subscribe(rx)
      const tx = b.channel(room, { config: { broadcast: { ack: true } } })
      await subscribe(tx)
      const status = await tx.send({ type: 'broadcast', event: 'ping', payload: { n: 1 } })
      assert.equal(status, 'ok')
      const msg = await withTimeout(got, 15_000, 'the broadcast message')
      assert.deepEqual(msg.payload, { n: 1 })
      assert.equal(msg.event, 'ping')
      await a.removeChannel(rx)
      await b.removeChannel(tx)
    })

    test('presence syncs, announces joins and leaves', async () => {
      const watcher = a.channel(`presence-${room}`, { config: { presence: { key: 'watcher' } } })
      const joined = new Promise((resolve) => watcher.on('presence', { event: 'join' }, ({ key }) => key === 'tracker' && resolve(key)))
      const left = new Promise((resolve) => watcher.on('presence', { event: 'leave' }, ({ key }) => key === 'tracker' && resolve(key)))
      await subscribe(watcher)
      const tracker = b.channel(`presence-${room}`, { config: { presence: { key: 'tracker' } } })
      await subscribe(tracker)
      assert.equal(await tracker.track({ name: 'tracker' }), 'ok')
      assert.equal(await withTimeout(joined, 15_000, 'the presence join'), 'tracker')
      const state = watcher.presenceState()
      assert.equal(state.tracker?.[0]?.name, 'tracker')
      await tracker.untrack()
      assert.equal(await withTimeout(left, 15_000, 'the presence leave'), 'tracker')
      await a.removeChannel(watcher)
      await b.removeChannel(tracker)
    })
  })
}
